(()=>{'use strict';const $=s=>document.querySelector(s),id='cb01-06';let learner=localStorage.getItem('learning-lab:learner')||'学习者一';const key=()=>`learning-lab:v1:${learner}:${id}`,read=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}};let saved=read(),stage=Math.max(0,Math.min(3,Number(saved.stage)||0)),evidence=saved.evidence||{mistakes:{},hints:0},state={},passed=false,errors=0,message='',tone='';const persist=()=>localStorage.setItem(key(),JSON.stringify({stage,evidence,updated:new Date().toISOString()}));
function init(){state=stage===0?{p:11,e:11,history:[],answer:null}:stage===1?{p:17,e:17,history:[],answer:null}:stage===2?{phase:0,p:12,e:12,history:[],answer:null}:{};passed=false;errors=0;message='';tone=''}
const spec=()=>stage===0?{name:'钠',symbol:'Na',target:10,correct:'Na+'}:stage===1?{name:'氯',symbol:'Cl',target:18,correct:'Cl-'}:state.phase===0?{name:'镁',symbol:'Mg',target:10,correct:'Mg2+'}:{name:'氧',symbol:'O',target:10,correct:'O2-'};
function electrons(n){let html='',remain=n;for(const [i,max,r] of [[0,2,23],[1,8,34],[2,8,42]]){const count=Math.min(remain,max);remain-=count;if(!count)continue;html+=`<span class="ring ${['one','two','three'][i]}" aria-hidden="true"></span>`;for(let j=0;j<count;j++){const a=2*Math.PI*j/count-Math.PI/2;html+=`<span class="electron" style="left:calc(50% + ${(Math.cos(a)*r).toFixed(1)}% - 11px);top:calc(50% + ${(Math.sin(a)*r).toFixed(1)}% - 11px)" aria-label="电子">e⁻</span>`}}return html}
function diagram(){const s=spec(),charge=state.p-state.e;return `<div class="atom-board" aria-label="${s.name}模型，${state.p} 个质子，${state.e} 个电子">${electrons(state.e)}<div class="core"><strong>${s.symbol}</strong><small>p⁺ × ${state.p}</small></div></div><div class="balance"><span>质子 p⁺<b>${state.p}</b></span><span>电子 e⁻<b>${state.e}</b></span><span>总电荷<b>${charge===0?'0':charge>0?'+'+charge:String(charge)}</b></span></div><div class="charge">${charge===0?'质子数 = 电子数：中性原子':charge>0?'失去电子后，正电荷多 '+charge+' 个':'得到电子后，负电荷多 '+(-charge)+' 个'}<br>质子数始终是 ${state.p}，元素仍是${s.name}。</div>`}
const opts=()=>{const s=spec();const options=stage===0?[['Na+','Na⁺'],['Na-','Na⁻'],['Na','Na']]:stage===1?[['Cl-','Cl⁻'],['Cl+','Cl⁺'],['Cl','Cl']]:state.phase===0?[['Mg2+','Mg²⁺'],['Mg+','Mg⁺'],['Mg2-','Mg²⁻']]:[['O2-','O²⁻'],['O-','O⁻'],['O2+','O²⁺']];return `<div class="answer-row">${options.map(([v,label])=>`<button type="button" data-action="choose" data-value="${v}" class="${state.answer===v?'selected':''}" aria-pressed="${state.answer===v}">${label}</button>`).join('')}</div>`};
function controls(){const s=spec(),start=stage===0?11:stage===1?17:state.phase===0?12:8;const min=Math.min(start,s.target),max=Math.max(start,s.target);return `<div class="control-row"><button type="button" data-action="lose" ${state.e<=min?'disabled':''}>− 移走 1 个电子</button><button type="button" data-action="gain" ${state.e>=max?'disabled':''}>＋ 放入 1 个电子</button></div><button type="button" data-action="undo" ${state.history.length?'':'disabled'}>↶ 撤销刚才一步</button>`}

function first(){return `<div class="stage-head"><div><span class="badge">第 1 关 · 失去电子</span><h2>钠原子少一个电子会怎样？</h2></div></div><p class="task">从中性的钠原子模型移走 1 个电子，再写离子符号。</p><div class="workbench"><div class="display"><h3>核内质子与核外电子</h3>${diagram()}</div><div class="tools"><h3>操作电子</h3>${controls()}<p class="mini">钠 Na：质子始终 11 个；电子由 11 变为 10。失去电子不是失去质子。</p><h3>符号写作</h3>${opts()}</div></div>`}
function second(){return `<div class="stage-head"><div><span class="badge">第 2 关 · 得到电子</span><h2>氯原子多一个电子会怎样？</h2></div></div><p class="task">给中性的氯原子模型加 1 个电子，再写离子符号。</p><div class="workbench"><div class="display"><h3>核内质子与核外电子</h3>${diagram()}</div><div class="tools"><h3>操作电子</h3>${controls()}<p class="mini">氯 Cl：质子始终 17 个；电子由 17 变为 18。多出 1 个负电荷。</p><h3>符号写作</h3>${opts()}</div></div>`}
function third(){const mg=state.phase===0;return `<div class="stage-head"><div><span class="badge">第 3 关 · 自主迁移</span><h2>两个电荷单位怎么写？</h2></div></div><p class="task">${mg?'先让镁模型失去 2 个电子，并写出镁离子。':'再让氧模型得到 2 个电子，并写出氧离子。'}</p><div class="workbench"><div class="display"><h3>${mg?'镁 Mg：12p、12e 起步':'氧 O：8p、8e 起步'}</h3>${diagram()}</div><div class="tools"><div class="phase">${mg?'任务 A · 镁：12e → 10e':'任务 B · 氧：8e → 10e'}</div><h3>操作电子</h3>${controls()}${mg?'':'<button type="button" data-action="restore">↶ 回到镁模型</button>'}<p class="mini">先数质子与电子的差，再把电荷数和正负号写在右上角。1 省略数字，2 不能省。</p><h3>选择当前离子符号</h3>${opts()}</div></div>`}
function summary(){return `<div class="stage-head"><span class="badge">本轮完成</span><h2>离子符号会读会写了！</h2></div><div class="summary"><ol><li>质子数不变，失去电子形成阳离子：Na⁺、Mg²⁺。</li><li>得到电子形成阴离子：Cl⁻、O²⁻。</li><li>电荷写在右上角；数字 1 不写，2 及以上要写。</li></ol><p>${Object.keys(evidence.mistakes).length?'复习建议：回到第 '+Object.keys(evidence.mistakes).join('、')+' 关，重新数质子与电子。':'试着说：为什么镁离子写 Mg²⁺，而不是 Mg⁺？'}</p></div><p class="task">记录只保存在当前浏览器的学习者档案。原子团离子将在后续知识点学习。</p>`}
function render(){$('#learner').value=learner;$('#steps').innerHTML=[0,1,2].map(i=>`<span class="${i<stage?'done':i===stage?'active':''}"></span>`).join('');$('#lab').innerHTML=[first,second,third,summary][stage]();$('#feedback').textContent=message;$('#feedback').className='feedback '+tone;$('#back').disabled=stage===0;$('#verify').hidden=stage===3;$('#next').hidden=!passed&&stage!==3;$('#next').textContent=stage===3?'返回知识地图 →':'下一关 →'}
function change(){passed=false;message='';tone='';render()}
function fail(reason){errors++;evidence.mistakes[stage+1]=(evidence.mistakes[stage+1]||0)+1;if(errors>=2){evidence.hints++;reason+=' 提示：'+['钠从 11e 减到 10e，11p 比 10e 多 1，写 Na⁺。','氯从 17e 加到 18e，负电多 1，写 Cl⁻。','镁 12p/10e 写 Mg²⁺，氧 8p/10e 写 O²⁻。'][stage]}message=reason;tone='bad';persist();render()}
function verify(){const s=spec();if(state.e!==s.target)return fail('先把电子数调到 '+s.target+'，比较质子数与电子数。');if(!state.history.length)return fail('请亲自操作电子后再判断。');if(state.answer!==s.correct)return fail('符号右上角的正负号与数字要对应质子数和电子数的差。');if(stage===2&&state.phase===0){state.phase=1;state.p=8;state.e=8;state.history=[];state.answer=null;message='Mg²⁺ 正确！现在给氧模型放入两个电子。';tone='good';render();return}passed=true;message=['正确！Na 比电子多 1 个正电荷，写 Na⁺。','正确！Cl 多 1 个电子，写 Cl⁻。','两种双电荷离子也写对了：Mg²⁺ 与 O²⁻。'][stage];tone='good';render()}
function move(n){stage=n;init();persist();render()}
$('#switch').onclick=()=>{learner=$('#learner').value.trim()||'学习者一';localStorage.setItem('learning-lab:learner',learner);saved=read();stage=Math.max(0,Math.min(3,Number(saved.stage)||0));evidence=saved.evidence||{mistakes:{},hints:0};init();render()};$('#learner').addEventListener('change',()=>$('#switch').click());$('#reset').onclick=()=>{localStorage.removeItem(key());evidence={mistakes:{},hints:0};move(0)};$('#back').onclick=()=>{if(stage>0)move(stage-1)};$('#verify').onclick=verify;$('#next').onclick=()=>{if(stage===3){location.href='../index.html';return}if(passed)move(stage+1)};
$('#lab').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(['lose','gain'].includes(a)){const s=spec(),delta=a==='lose'?-1:1;const min=Math.min(s.target,stage===0?11:stage===1?17:state.phase===0?12:8),max=Math.max(s.target,stage===0?11:stage===1?17:state.phase===0?12:8);if(state.e+delta>=min&&state.e+delta<=max){state.history.push(state.e);state.e+=delta;change()}}else if(a==='undo'&&state.history.length){state.e=state.history.pop();change()}else if(a==='choose'){state.answer=b.dataset.value;change()}else if(a==='restore'&&stage===2){state.phase=0;state.p=12;state.e=12;state.history=[];state.answer=null;change()}});init();render()})();
