(()=>{'use strict';
const id='cb01-01', $=s=>document.querySelector(s), key=()=>`learning-lab:v2:${learner}:${id}`;
let learner=localStorage.getItem('learning-lab:learner')||'学习者一';
const read=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}};
let saved=read(), stage=Math.max(0,Math.min(3,Number(saved.stage)||0)), evidence=saved.evidence||{mistakes:{},hints:0}, state={};let passed=false,errors=0,message='',tone='';
const save=()=>localStorage.setItem(key(),JSON.stringify({stage,evidence,updated:new Date().toISOString()}));
function resetState(){state=stage===0?{a:4,b:0,choice:null,history:[]}:stage===1?{salt:false,micro:false,seenMicro:false,left:null,right:null}:stage===2?{water:null,air:null,inspected:{water:false,air:false},focus:null}:{};passed=false;errors=0;message='';tone=''}
function stepBar(){return [0,1,2].map(i=>`<span class="${i<stage?'done':i===stage?'active':''}"></span>`).join('')}
const atom=(kind,n)=>Array.from({length:n},()=>`<span class="atom ${kind==='B'?'b':''}" aria-label="物质 ${kind}">${kind}</span>`).join('');
const molecule=(kind,n)=>Array.from({length:n},()=>`<span class="molecule" aria-label="${kind==='水'?'水分子示意':kind==='氮'?'氮气示意':'氧气示意'}">${kind==='水'?'<i class="bead h">氢</i><i class="bead">氧</i><i class="bead h">氢</i>':kind==='氮'?'<i class="bead n">氮</i><i class="bead n">氮</i>':'<i class="bead o">氧</i><i class="bead o">氧</i>'}</span>`).join('');
const choice=(target,val,label)=>`<button type="button" class="option ${state[target]===val?'selected':''}" data-action="choose" data-target="${target}" data-value="${val}" aria-pressed="${state[target]===val}">${label}</button>`;
function first(){return `<div class="stage-head"><div><span class="badge">第 1 关 · 亲手配</span><h2>让一种物质变成两种</h2></div></div><p class="task">把 A 或 B 放进容器，做出一份混合物。先看粒子变化，再给它贴分类标签。</p><div class="workbench"><div class="display"><h3>透明容器 · 点击或拖入材料</h3><div class="vessel" id="vessel" aria-label="容器中有 ${state.a} 个 A 和 ${state.b} 个 B"><div class="contents">${atom('A',state.a)}${atom('B',state.b)}</div></div><div class="readout">现在有 <b>${state.a}</b> 个 A、<b>${state.b}</b> 个 B · ${state.b?'看见两种物质':'目前只有一种物质'}</div></div><div class="tools"><h3>材料台</h3><button type="button" draggable="true" data-token="A" data-action="addA">🔵 放入 A</button><button type="button" draggable="true" data-token="B" data-action="addB">🟨 放入 B</button><p class="toolhint">可点击，也可拖到容器。A 与 B 代表两种不同物质，不是元素符号。</p><button type="button" data-action="undo" ${state.history.length?'':'disabled'}>↶ 撤销刚才放入</button><h3>我给样品贴标签</h3><div class="selector">${choice('choice','pure','纯净物')}${choice('choice','mixture','混合物')}</div></div></div>`}
const microBits=(salt)=>`<div class="microbits">${Array.from({length:5},()=>'<span class="microbit">水</span>').join('')}${salt?Array.from({length:3},()=>'<span class="microbit salt">盐</span>').join(''):''}</div>`;
function second(){return `<div class="stage-head"><div><span class="badge">第 2 关 · 换视野</span><h2>清澈，就一定纯净吗？</h2></div><button type="button" class="optic" data-action="micro" aria-pressed="${state.micro}">${state.micro?'🔍 回到肉眼':'🔍 打开微观视野'}</button></div><p class="task">向右杯加食盐并搅匀。两杯都清澈时，打开微观视野找证据。</p><div class="workbench"><div class="display ${state.micro?'micro':''}"><h3>${state.micro?'微观模型 · 看物质种类':'肉眼视野 · 两杯都清澈'}</h3><div class="cups"><div class="cup-wrap"><strong>左杯 · 蒸馏水</strong><div class="cup" aria-label="左杯：${state.micro?'只有水的模型':'清澈液体'}">${state.micro?microBits(false):''}</div></div><div class="cup-wrap"><strong>右杯 · ${state.salt?'食盐水':'蒸馏水'}</strong><div class="cup" id="right-cup" aria-label="右杯：${state.micro?(state.salt?'水和食盐的模型':'只有水的模型'):'清澈液体'}">${state.micro?microBits(state.salt):''}</div></div></div><div class="readout">${state.micro?(state.salt?'左杯 1 种物质；右杯 2 种物质':'两杯现在都只有水'):'肉眼所见：两杯外观相似，不能据此断定组成'}</div></div><div class="tools"><h3>操作台</h3><button type="button" draggable="true" data-token="salt" data-action="salt" ${state.salt?'disabled':''}>🧂 ${state.salt?'食盐已加入右杯':'向右杯加入食盐'}</button><button type="button" data-action="clearSalt" ${state.salt?'':'disabled'}>↶ 复位右杯</button><p class="toolhint">食盐已溶解时，肉眼仍看不见它。微观图只是“含多种物质”的分类示意，不画真实离子。</p><h3>给两杯分类</h3><div>左杯：${choice('left','pure','纯净物')}${choice('left','mixture','混合物')}</div><div>右杯：${choice('right','pure','纯净物')}${choice('right','mixture','混合物')}</div></div></div>`}
function third(){return `<div class="stage-head"><div><span class="badge">第 3 关 · 自己解释</span><h2>元素多 ≠ 物质多</h2></div></div><p class="task">分别点开两个样品看“物质种类”。纯水含氢、氧两种元素；洁净空气含多种气体。</p><div class="workbench"><div class="display"><div class="comparison"><div class="model ${state.focus==='water'?'active':''}"><h3>纯水</h3><div class="molecules">${molecule('水',4)}</div><small>每一组都代表同一种水物质</small><button type="button" data-action="inspect" data-sample="water">🔎 检查纯水组成</button></div><div class="model ${state.focus==='air'?'active':''}"><h3>洁净空气</h3><div class="molecules">${molecule('氮',2)}${molecule('氧',2)}</div><small>两类图块代表不同气体物质</small><button type="button" data-action="inspect" data-sample="air">🔎 检查空气组成</button></div></div><div class="readout">${state.focus==='water'?'纯水：水这种物质只有 1 种；一个水分子可含不同元素。':state.focus==='air'?'空气：氮气、氧气等不同物质共同存在。':'点样品查看依据，别把元素种类当物质种类。'}</div></div><div class="tools"><h3>纯水属于</h3>${choice('water','pure','纯净物')}${choice('water','mixture','混合物')}<h3>洁净空气属于</h3>${choice('air','pure','纯净物')}${choice('air','mixture','混合物')}<p class="toolhint">模型只表达“相同或不同的物质”，并非完整分子比例或空间结构。</p></div></div>`}
function summary(){const wrong=Object.keys(evidence.mistakes);return `<div class="stage-head"><span class="badge">本轮完成</span><h2>会看组成，才会分类</h2></div><div class="summary"><ol><li>一种物质 → 纯净物；两种或更多 → 混合物。</li><li>透明的食盐水仍含水和食盐。</li><li>水可含两种元素，却仍是一种物质。</li></ol><p>${wrong.length?`复习建议：回看第 ${wrong.join('、')} 关，再做一遍。提示使用 ${evidence.hints} 次。`:'可以向家人解释：为什么洁净空气仍是混合物？'}</p></div><p class="task">这些学习记录只保存在当前浏览器的学习者档案中。</p>`}
function render(){ $('#learner').value=learner;$('#steps').innerHTML=stepBar();$('#lab').innerHTML=stage===0?first():stage===1?second():stage===2?third():summary();$('#feedback').textContent=message;$('#feedback').className='feedback '+tone;$('#back').disabled=stage===0;$('#verify').hidden=stage===3;$('#next').hidden=!passed&&stage!==3;$('#next').textContent=stage===3?'返回知识地图 →':'下一关 →';}
function changed(){passed=false;message='';tone='';render()}
function add(kind){if(stage!==0||state.a+state.b>=11)return;state.history.push([state.a,state.b]);state[kind.toLowerCase()]++;changed()}
function verify(){let ok=false,reason='';if(stage===0){ok=state.b>0&&state.choice==='mixture';reason=state.b===0?'现在只有 A。请亲手加入 B，观察容器里的变化。':'容器中有 A 和 B 两种物质，请把标签改成“混合物”。'}else if(stage===1){ok=state.salt&&state.seenMicro&&state.left==='pure'&&state.right==='mixture';reason=!state.salt?'先把食盐加入右杯。':!state.seenMicro?'打开微观视野，看见右杯还有食盐。':'看的是物质种类：左杯只有水，右杯有水和食盐。'}else if(stage===2){ok=state.inspected.water&&state.inspected.air&&state.water==='pure'&&state.air==='mixture';reason=(!state.inspected.water||!state.inspected.air)?'请分别检查两个样品的组成，再作判断。':'纯水是一种物质，空气含不同气体；数物质，不数元素。'}if(ok){passed=true;message=['做到了！放入 B 后，容器从一种物质变成两种。','看见了吗？两杯一样清澈，微观组成却不同。','判断正确：水含不同元素仍是纯净物，空气是混合物。'][stage];tone='good'}else{errors++;evidence.mistakes[stage+1]=(evidence.mistakes[stage+1]||0)+1;if(errors>=2){evidence.hints++;reason+=' 提示：'+['试着放入橙色 B。','打开微观视野，比较两杯的物质种类。','两杯中看“图块代表几种物质”。'][stage]}message=reason;tone='bad';save()}render()}
function move(to){stage=to;resetState();save();render()}
$('#switch').onclick=()=>{learner=$('#learner').value.trim()||'学习者一';localStorage.setItem('learning-lab:learner',learner);saved=read();stage=Math.max(0,Math.min(3,Number(saved.stage)||0));evidence=saved.evidence||{mistakes:{},hints:0};resetState();render()};
$('#learner').addEventListener('change',()=>$('#switch').click());
$('#reset').onclick=()=>{localStorage.removeItem(key());evidence={mistakes:{},hints:0};move(0)};
$('#back').onclick=()=>{if(stage>0)move(stage-1)};
$('#verify').onclick=verify;
$('#next').onclick=()=>{if(stage===3){location.href='../index.html';return}if(passed)move(stage+1)};
$('#lab').addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='addA')add('A');else if(a==='addB')add('B');else if(a==='undo'&&stage===0&&state.history.length){[state.a,state.b]=state.history.pop();changed()}else if(a==='choose'){state[b.dataset.target]=b.dataset.value;changed()}else if(a==='salt'&&stage===1){state.salt=true;if(state.micro)state.seenMicro=true;changed()}else if(a==='clearSalt'&&stage===1){state.salt=false;state.seenMicro=false;changed()}else if(a==='micro'&&stage===1){state.micro=!state.micro;if(state.micro&&state.salt)state.seenMicro=true;changed()}else if(a==='inspect'&&stage===2){state.focus=b.dataset.sample;state.inspected[state.focus]=true;changed()}});
$('#lab').addEventListener('dragstart',e=>{let x=e.target.closest('[data-token]');if(x&&e.dataTransfer){e.dataTransfer.setData('text/plain',x.dataset.token);e.dataTransfer.effectAllowed='copy'}});
$('#lab').addEventListener('dragover',e=>{if(e.target.closest('#vessel,#right-cup'))e.preventDefault()});
$('#lab').addEventListener('drop',e=>{const dest=e.target.closest('#vessel,#right-cup');if(!dest)return;e.preventDefault();const value=e.dataTransfer?.getData('text/plain');if(dest.id==='vessel'&&['A','B'].includes(value))add(value);if(dest.id==='right-cup'&&value==='salt'&&stage===1){state.salt=true;if(state.micro)state.seenMicro=true;changed()}});
resetState();render();})();
