(()=>{'use strict';const $=s=>document.querySelector(s),id='cb01-05';let learner=localStorage.getItem('learning-lab:learner')||'学习者一';const key=()=>`learning-lab:v1:${learner}:${id}`,read=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}};let saved=read(),stage=Math.max(0,Math.min(3,Number(saved.stage)||0)),evidence=saved.evidence||{mistakes:{},hints:0},state={},passed=false,errors=0,message='',tone='';const persist=()=>localStorage.setItem(key(),JSON.stringify({stage,evidence,updated:new Date().toISOString()}));
function init(){state=stage===0?{p:0,n:0,e:0,history:[]}:stage===1?{p:6,n:6,e:6,seen13:false,same:null,weight:null}:stage===2?{p:0,n:0,e:0,touched:{},answer:null}:{};passed=false;errors=0;message='';tone=''}
const pips=(type,n)=>Array.from({length:n},()=>`<span class="particle ${type}" aria-label="${type==='p'?'质子':type==='n'?'中子':'电子'}">${type==='p'?'p⁺':type==='n'?'n':'e⁻'}</span>`).join('');
function electrons(n){let remaining=n,html='';for(const [index,cap,radius] of [[0,2,23],[1,8,34],[2,8,42]]){const count=Math.min(remaining,cap);remaining-=count;if(!count)continue;html+=`<span class="orbit shell${index}" aria-hidden="true"></span>`;for(let i=0;i<count;i++){const a=(i/count)*Math.PI*2-Math.PI/2;const x=Math.cos(a)*radius,y=Math.sin(a)*radius;html+=`<span class="particle e" style="left:calc(50% + ${x.toFixed(1)}% - 11px);top:calc(50% + ${y.toFixed(1)}% - 11px)" aria-label="电子">e⁻</span>`}}return html}
function visual(){const {p,n,e}=state;const label=stage===0?'氦原子目标模型':stage===1?`碳原子模型 · ${p+n} 核子`:'目标：钠原子模型';return `<div class="atom-board" aria-label="${label}，${p} 个质子、${n} 个中子、${e} 个电子">${electrons(e)}<div class="nucleus">${p+n?(p+n<=6?pips('p',p)+pips('n',n):'<span class="count-chip p">p⁺ ×'+p+'</span><span class="count-chip n">n ×'+n+'</span>'):'<span class="empty-nucleus">先配置核内粒子</span>'}</div></div><div class="stats"><span>质子 p⁺<b>${p}</b></span><span>中子 n<b>${n}</b></span><span>电子 e⁻<b>${e}</b></span></div><div class="mass">核内粒子数（质量数） <b>${p+n}</b> = ${p} 个质子 + ${n} 个中子<br>${p?`电荷读数：${p===e?'中性':p>e?'正 '+(p-e):'负 '+(e-p)}`:'尚未形成目标模型'} · 电子质量很小，初步估算时忽略</div>`}
const choice=(field,value,label)=>`<button type="button" data-action="choose" data-field="${field}" data-value="${value}" class="${state[field]===value?'selected':''}" aria-pressed="${state[field]===value}">${label}</button>`;
function first(){return `<div class="stage-head"><div><span class="badge">第 1 关 · 组装</span><h2>搭一颗中性的氦原子</h2></div></div><p class="task">向原子核放 2 个质子、2 个中子，核外放 2 个电子。</p><div class="workbench"><div class="display"><h3>原子结构示意</h3>${visual()}</div><div class="tools"><h3>粒子托盘</h3><div class="controls"><button type="button" data-action="add" data-kind="p" ${state.p===2?'disabled':''}>＋ 质子 p⁺</button><button type="button" data-action="add" data-kind="n" ${state.n===2?'disabled':''}>＋ 中子 n</button><button type="button" data-action="add" data-kind="e" ${state.e===2?'disabled':''}>＋ 电子 e⁻</button><button type="button" data-action="undo" ${state.history.length?'':'disabled'}>↶ 撤销一步</button></div><p class="mini">质子带正电，电子带负电，中子不带电。质子数 = 电子数时，这个模型整体不带电。</p><p class="mini">氦 He：这里用 2p、2n、2e 的氦-4模型。</p></div></div>`}
function second(){return `<div class="stage-head"><div><span class="badge">第 2 关 · 改一个中子</span><h2>增加中子，会变成别的元素吗？</h2></div></div><p class="task">先看 6p、6n、6e 的碳-12模型，再给原子核加一个中子。</p><div class="workbench"><div class="display"><h3>原子核与核外</h3>${visual()}<div class="comparator"><div class="compare-card ${state.n===6?'active':''}"><strong>碳-12</strong><p>6 个质子 + 6 个中子</p><div class="small-atom">${pips('p',6)+pips('n',6)}</div><p>质量数 12</p></div><div class="compare-card ${state.n===7?'active':''}"><strong>碳-13</strong><p>6 个质子 + 7 个中子</p><div class="small-atom">${pips('p',6)+pips('n',7)}</div><p>质量数 13</p></div></div></div><div class="tools"><h3>只调整中子</h3><button type="button" data-action="neutron" data-delta="1" ${state.n===7?'disabled':''}>＋ 增加 1 个中子</button><button type="button" data-action="neutron" data-delta="-1" ${state.n===6?'disabled':''}>↶ 减去 1 个中子</button><p class="mini">质子仍是 6，电子仍是 6。碳-12和碳-13是碳的两种原子模型。</p><h3>增加中子后</h3><div class="answer-row">${choice('same','yes','仍是碳')}${choice('same','no','变成别的元素')}</div><div class="answer-row">${choice('weight','up','质量数增 1')}${choice('weight','same','质量数不变')}</div><p class="mini">质量数恰好是核内质子数 + 中子数。自然界碳元素的相对原子质量约 12.01，是平均值；不要把它和碳-13的质量数 13 画等号。</p></div></div>`}
function third(){return `<div class="stage-head"><div><span class="badge">第 3 关 · 独立配置</span><h2>完成钠-23的原子档案</h2></div></div><p class="task">调节三条数值条，配置 11 个质子、12 个中子、11 个电子，再估算质量数。</p><div class="workbench"><div class="display"><h3>核内 / 核外模型</h3><div id="visual">${visual()}</div></div><div class="tools"><h3>档案目标：钠 Na</h3><div class="sliders">${[['p','质子 p⁺',12,11],['n','中子 n',14,12],['e','电子 e⁻',12,11]].map(([k,label,max,target])=>`<label>${label}：<strong id="val-${k}">${state[k]}</strong>　目标 ${target}<input type="range" data-count="${k}" min="0" max="${max}" value="${state[k]}" aria-label="${label}数量"></label>`).join('')}</div><p class="mini">拖动或用键盘方向键调整。只是在配置模型，并非通过实验改变原子。</p><h3>估算质量数是多少？</h3><div class="answer-row">${choice('answer','23','23')}${choice('answer','34','34')}${choice('answer','11','11')}</div></div></div>`}
function summary(){return `<div class="stage-head"><span class="badge">本轮完成</span><h2>读懂核内与核外了！</h2></div><div class="summary"><ol><li>原子核里有质子、中子；核外有电子。</li><li>中性原子：质子数 = 电子数。质子数决定元素种类。</li><li>质量数 = 质子数 + 中子数；初中可据此估算单个原子的相对质量。</li></ol><p>${Object.keys(evidence.mistakes).length?'复习建议：回看第 '+Object.keys(evidence.mistakes).join('、')+' 关，解释哪个数变了。':'试解释：碳-12变成碳-13，什么没有变？'}</p></div><p class="task">进度只保存在本机当前浏览器的学习者档案。</p>`}
function render(){$('#learner').value=learner;$('#steps').innerHTML=[0,1,2].map(i=>`<span class="${i<stage?'done':i===stage?'active':''}"></span>`).join('');$('#lab').innerHTML=[first,second,third,summary][stage]();$('#feedback').textContent=message;$('#feedback').className='feedback '+tone;$('#back').disabled=stage===0;$('#verify').hidden=stage===3;$('#next').hidden=!passed&&stage!==3;$('#next').textContent=stage===3?'返回知识地图 →':'下一关 →'}
function change(){passed=false;message='';tone='';render()}
function fail(reason){errors++;evidence.mistakes[stage+1]=(evidence.mistakes[stage+1]||0)+1;if(errors>=2){evidence.hints++;reason+=' 提示：'+['氦-4模型需要 2p、2n、2e；试着数核内与核外。','只增加中子，质子数仍为 6；比较核内粒子总数。','钠-23的模型要求 11p、12n、11e，质量数只算核内粒子。'][stage]}message=reason;tone='bad';persist();render()}
function verify(){if(stage===0){if(state.p!==2||state.n!==2||state.e!==2)return fail('还没组装成氦-4的中性原子：请数到 2p、2n、2e。');passed=true;message='搭好了！核内 2p+2n，核外 2e；质子与电子数相等。';tone='good'}else if(stage===1){if(!state.seen13||state.n!==7)return fail('先加入一个中子并保持在碳-13模型，再比较两个模型。');if(state.same!=='yes'||state.weight!=='up')return fail('质子数没变，仍是碳；核内多一个中子，质量数从 12 变 13。');passed=true;message='正确！仍是碳，质量数增 1；元素平均相对原子质量另有含义。';tone='good'}else if(stage===2){if(state.p!==11||state.n!==12||state.e!==11)return fail('对照目标调节三条数值：11p、12n、11e。');if(Object.keys(state.touched).length<3)return fail('请亲自调节三项数值，再检查模型。');if(state.answer!=='23')return fail('质量数只数质子和中子：11 + 12 = 23；电子不计入。');passed=true;message='完成！钠原子模型 11p、12n、11e，质量数 23。';tone='good'}render()}
function move(n){stage=n;init();persist();render()}
$('#switch').onclick=()=>{learner=$('#learner').value.trim()||'学习者一';localStorage.setItem('learning-lab:learner',learner);saved=read();stage=Math.max(0,Math.min(3,Number(saved.stage)||0));evidence=saved.evidence||{mistakes:{},hints:0};init();render()};$('#learner').addEventListener('change',()=>$('#switch').click());$('#reset').onclick=()=>{localStorage.removeItem(key());evidence={mistakes:{},hints:0};move(0)};$('#back').onclick=()=>{if(stage>0)move(stage-1)};$('#verify').onclick=verify;$('#next').onclick=()=>{if(stage===3){location.href='../index.html';return}if(passed)move(stage+1)};
$('#lab').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='add'&&stage===0){const k=b.dataset.kind;if(state[k]<2){state.history.push(k);state[k]++;change()}}else if(a==='undo'&&stage===0&&state.history.length){state[state.history.pop()]--;change()}else if(a==='neutron'&&stage===1){state.n+=Number(b.dataset.delta);if(state.n===7)state.seen13=true;change()}else if(a==='choose'){state[b.dataset.field]=b.dataset.value;change()}});
$('#lab').addEventListener('input',e=>{const b=e.target.closest('[data-count]');if(!b||stage!==2)return;const k=b.dataset.count;state[k]=Number(b.value);state.touched[k]=true;passed=false;message='';tone='';$('#visual').innerHTML=visual();$('#val-'+k).textContent=state[k];$('#next').hidden=true;$('#feedback').textContent='';$('#feedback').className='feedback'});
init();render()})();
