(()=>{'use strict';
const $=s=>document.querySelector(s), lesson='cb01-02';
let learner=localStorage.getItem('learning-lab:learner')||'学习者一';
const key=()=>`learning-lab:v1:${learner}:${lesson}`;
const read=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}};
let record=read(),stage=Math.max(0,Math.min(3,Number(record.stage)||0));
let evidence=record.evidence||{mistakes:{},hints:0},state={},passed=false,errors=0,message='',tone='';
function save(){localStorage.setItem(key(),JSON.stringify({stage,evidence,updated:new Date().toISOString()}))}
function initialize(){state=stage===0?{o:0,answer:null}:stage===1?{c:false,o:0,phase:0,swapped:false,type:null,oxide:null}:stage===2?{selected:null,placed:{}}:{};passed=false;errors=0;message='';tone=''}
function ball(atom){return `<span class="ball ${atom.toLowerCase()}" aria-label="${{O:'氧',C:'碳',H:'氢',N:'氮'}[atom]}原子">${atom}</span>`}
function model(name){if(name==='oxygen')return ball('O')+'<span class="bond"></span>'+ball('O');if(name==='nitrogen')return ball('N')+'<span class="bond"></span>'+ball('N');if(name==='carbon')return ball('O')+'<span class="bond"></span>'+ball('C')+'<span class="bond"></span>'+ball('O');if(name==='methane')return ball('H')+ball('H')+ball('C')+ball('H')+ball('H');return ''}
function pick(field,value,label){return `<button type="button" data-action="pick" data-field="${field}" data-value="${value}" class="${state[field]===value?'selected':''}" aria-pressed="${state[field]===value}">${label}</button>`}
function branch(lit){return `<div class="branch"><span class="${lit==='single'?'lit':''}">一种元素 → 单质</span><span class="${['compound','oxide','other'].includes(lit)?'lit':''}">多种元素 → 化合物</span><span class="${lit==='oxide'?'lit':''}">化合物含氧 + 另一元素 → 氧化物</span><span class="${lit==='other'?'lit':''}">化合物不含氧 → 非氧化物</span></div>`}
function first(){return `<div class="stage-head"><div><span class="badge">第 1 关 · 组装</span><h2>只有氧原子，就是什么？</h2></div></div><p class="task">点两次“加入氧原子”，拼出一组氧气模型，再选类别。</p><div class="workbench"><div class="display"><h3>氧气模型 O₂（两个氧原子）</h3><div class="specimen"><div class="atoms">${state.o?ball('O'):''}${state.o===2?'<span class="bond"></span>'+ball('O'):''}</div><strong>${state.o===2?'O₂ · 氧气':state.o===1?'还差一个氧原子':'空模型'}</strong><small>只有组装完成才判断物质类别；O 是氧元素符号。</small></div>${branch(state.o===2?'single':null)}</div><div class="tools"><h3>组装台</h3><button type="button" data-action="addO" ${state.o===2?'disabled':''}>＋ 加入氧原子 O</button><button type="button" data-action="removeO" ${state.o===0?'disabled':''}>↶ 撤回一个氧原子</button><p class="mini">模型只表达组成，不代表在实验中把原子手工拼接。</p><h3>完成后贴标签</h3><div class="category">${pick('answer','single','单质')}${pick('answer','compound','化合物')}</div></div></div>`}
function second(){const a=state.phase===0,complete=state.c&&state.o===2;const atoms=a?`${state.o?ball('O'):''}${state.c?ball('C'):''}${state.o===2?ball('O'):''}`:state.swapped?model('methane'):model('carbon');return `<div class="stage-head"><div><span class="badge">第 2 关 · 比较</span><h2>化合物里再找氧化物</h2></div></div><p class="task">先用 1 个碳和 2 个氧组成二氧化碳；随后把它换成甲烷，观察分类变化。</p><div class="workbench"><div class="display"><h3>${a?'二氧化碳 CO₂':'甲烷 CH₄ 与二氧化碳 CO₂'}</h3><div class="specimen"><div class="atoms">${atoms}</div><strong>${a?(complete?'CO₂ · 二氧化碳':'模型尚未拼好'):(state.swapped?'CH₄ · 甲烷':'CO₂ · 二氧化碳')}</strong><small>${a?'氧是氧元素，碳是碳元素。':state.swapped?'有碳和氢，没有氧。':'点击按钮换成另一种完整的物质模型。'}</small></div>${branch(a?(complete?'oxide':null):state.swapped?'other':'oxide')}</div><div class="tools"><div class="subphase">${a?'任务 A：组装并判断 CO₂':'任务 B：把 CO₂ 换成 CH₄ 再判断'}</div>${a?`<button type="button" data-action="addC" ${state.c?'disabled':''}>＋ 加入碳原子 C</button><button type="button" data-action="addO" ${state.o===2?'disabled':''}>＋ 加入氧原子 O</button><button type="button" data-action="undoBuild" ${!state.c&&!state.o?'disabled':''}>↶ 撤回一枚原子</button>`:`<button type="button" data-action="swap" ${state.swapped?'disabled':''}>🔄 换成甲烷模型 CH₄</button><button type="button" data-action="restore">↶ 回到二氧化碳模型</button>`}<h3>它属于</h3><div class="category">${pick('type','compound','化合物')}${pick('type','single','单质')}</div><h3>它是不是氧化物？</h3><div class="category">${pick('oxide','yes','是氧化物')}${pick('oxide','no','不是氧化物')}</div><p class="mini">氧化物必须是只含两种元素、其中一种为氧元素的化合物。甲烷仅用于虚拟分类，不涉及燃烧。</p></div></div>`}
const samples=[['oxygen','氧气 O₂','两个氧原子'],['carbon','二氧化碳 CO₂','碳和氧'],['methane','甲烷 CH₄','碳和氢'],['air','空气','多种气体']];
const bins=[['single','纯净物 → 单质'],['oxide','纯净物 → 化合物 → 氧化物'],['other','纯净物 → 化合物 → 非氧化物'],['mixture','混合物']];
function third(){return `<div class="stage-head"><div><span class="badge">第 3 关 · 独立分类</span><h2>把样品送进分类树</h2></div></div><p class="task">先点一个样品，再点它应进入的分类格。放错了可以重新放。</p><div class="sort-stage"><div><h3>样品卡</h3><div class="samples">${samples.map(([id,name,detail])=>`<button type="button" class="sample ${state.selected===id?'selected':''}" data-action="select" data-id="${id}" aria-pressed="${state.selected===id}"><span class="sample-visual" aria-hidden="true">${id==='air'?model('nitrogen')+model('oxygen'):model(id)}</span><span>${name}<br><small>${detail}</small></span><em>${state.placed[id]?'已放入 ↗':'点我'}</em></button>`).join('')}</div></div><div><h3>分类树</h3><div class="bins">${bins.map(([id,name])=>`<button type="button" class="bin" data-action="place" data-id="${id}"><strong>${name}</strong><span class="placed">${samples.filter(([s])=>state.placed[s]===id).map(x=>x[1]).join(' · ')||'等待样品…'}</span></button>`).join('')}</div></div><p class="sort-help">${state.selected?'已选中 '+samples.find(x=>x[0]===state.selected)[1]+'，现在点分类格。':'选中样品后点分类格；分类看物质种类和元素种类。'}</p></div>`}
function summary(){return `<div class="stage-head"><span class="badge">本轮完成</span><h2>分类树走通了！</h2></div><div class="summary"><p>先看样品含几种物质：多种物质是混合物；一种物质才继续判断。</p><ol><li>纯净物只含一种元素 → 单质（如 O₂）。</li><li>纯净物含多种元素 → 化合物（如 CO₂、CH₄）。</li><li>只含两种元素且其中一种是氧 → 氧化物（如 CO₂）。</li></ol><p>${Object.keys(evidence.mistakes).length?'复习建议：再试第 '+Object.keys(evidence.mistakes).join('、')+' 关，解释放错的依据。':'试着用自己的话解释：甲烷为什么不是氧化物？'}</p></div><p class="task">学习记录仅保存在当前浏览器中。</p>`}
function render(){ $('#learner').value=learner;$('#steps').innerHTML=[0,1,2].map(i=>`<span class="${i<stage?'done':i===stage?'active':''}"></span>`).join('');$('#lab').innerHTML=[first,second,third,summary][stage]();$('#feedback').textContent=message;$('#feedback').className='feedback '+tone;$('#back').disabled=stage===0;$('#verify').hidden=stage===3;$('#next').hidden=!passed&&stage!==3;$('#next').textContent=stage===3?'返回知识地图 →':'下一关 →'}
function change(){passed=false;message='';tone='';render()}
function fail(reason){errors++;evidence.mistakes[stage+1]=(evidence.mistakes[stage+1]||0)+1;if(errors>=2){evidence.hints++;reason+=' 提示：'+['点两次“加入氧原子”，再数元素种类。','CO₂ 有碳和氧；CH₄ 有碳和氢。氧化物必须含氧。','先看是不是一种物质，再看元素是否含氧。'][stage]}message=reason;tone='bad';save();render()}
function verify(){if(stage===0){if(state.o!==2)return fail('模型还没有组成氧气；请加入两个氧原子。');if(state.answer!=='single')return fail('氧气只含氧元素，请选“单质”。');passed=true;message='氧气 O₂ 是一种物质，只含氧元素，属于单质。';tone='good'}
else if(stage===1){if(state.phase===0){if(!state.c||state.o!==2)return fail('先拼出 CO₂：1 个碳原子和 2 个氧原子。');if(state.type!=='compound'||state.oxide!=='yes')return fail('CO₂ 含碳、氧两种元素：它是化合物，也符合氧化物条件。');state.phase=1;state.type=null;state.oxide=null;message='正确！现在把完整模型换成甲烷 CH₄，再判断一次。';tone='good'}else{if(!state.swapped)return fail('请先点“换成甲烷模型”，观察氧原子是否还在。');if(state.type!=='compound'||state.oxide!=='no')return fail('CH₄ 含碳和氢，是化合物；没有氧，因此不是氧化物。');passed=true;message='对！换模型后仍是化合物，但不再是氧化物。';tone='good'}}
else if(stage===2){const expected={oxygen:'single',carbon:'oxide',methane:'other',air:'mixture'};const missing=samples.filter(([id])=>!state.placed[id]);if(missing.length)return fail('还有 '+missing.map(x=>x[1]).join('、')+' 没放入分类树。');const wrong=samples.filter(([id])=>state.placed[id]!==expected[id]);if(wrong.length)return fail(wrong.map(x=>x[1]).join('、')+' 放错了；请逐一检查“物质种类 → 元素种类 → 是否含氧”。');passed=true;message='四个样品都归位了！氧化物是化合物中的一种。';tone='good'}render()}
function move(n){stage=n;initialize();save();render()}
$('#switch').onclick=()=>{learner=$('#learner').value.trim()||'学习者一';localStorage.setItem('learning-lab:learner',learner);record=read();stage=Math.max(0,Math.min(3,Number(record.stage)||0));evidence=record.evidence||{mistakes:{},hints:0};initialize();render()};
$('#learner').addEventListener('change',()=>$('#switch').click());
$('#reset').onclick=()=>{localStorage.removeItem(key());evidence={mistakes:{},hints:0};move(0)};
$('#back').onclick=()=>{if(stage>0)move(stage-1)};
$('#verify').onclick=verify;
$('#next').onclick=()=>{if(stage===3){location.href='../index.html';return}if(passed)move(stage+1)};
$('#lab').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='addO'&&stage===0&&state.o<2){state.o++;change()}else if(a==='removeO'&&stage===0&&state.o){state.o--;change()}else if(a==='addC'&&stage===1&&!state.c){state.c=true;change()}else if(a==='addO'&&stage===1&&state.phase===0&&state.o<2){state.o++;change()}else if(a==='undoBuild'&&stage===1&&state.phase===0){if(state.o)state.o--;else state.c=false;change()}else if(a==='swap'&&stage===1&&state.phase===1){state.swapped=true;change()}else if(a==='restore'&&stage===1){state.phase=0;state.swapped=false;state.type=null;state.oxide=null;change()}else if(a==='pick'){state[b.dataset.field]=b.dataset.value;change()}else if(a==='select'&&stage===2){state.selected=b.dataset.id;change()}else if(a==='place'&&stage===2){if(state.selected){state.placed[state.selected]=b.dataset.id;state.selected=null;change()}else{message='先点一张样品卡，再点分类格。';tone='bad';render()}}});
initialize();render();
})();
