(()=>{'use strict';const $=s=>document.querySelector(s),lesson='cb01-03';let learner=localStorage.getItem('learning-lab:learner')||'学习者一';const key=()=>`learning-lab:v1:${learner}:${lesson}`;const read=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}};let saved=read(),stage=Math.max(0,Math.min(3,Number(saved.stage)||0)),evidence=saved.evidence||{mistakes:{},hints:0},state={},passed=false,errors=0,message='',tone='';const persist=()=>localStorage.setItem(key(),JSON.stringify({stage,evidence,updated:new Date().toISOString()}));
function init(){state=stage===0?{zoom:false,inspected:false,answer:null}:stage===1?{sample:'oxygen',zoom:false,seen:{oxygen:false,iron:false},oxygen:null,iron:null}:stage===2?{selected:null,placed:{}}:{};passed=false;errors=0;message='';tone=''}
const dot=x=>`<span class="dot ${x.toLowerCase()}" aria-label="${{H:'氢',O:'氧',Fe:'铁'}[x]}原子">${x}</span>`;
const molecule=(kind,hi=false)=>`<span class="group ${hi?'highlight':''}" aria-label="一个${kind==='water'?'水':'氧气'}分子模型">${kind==='water'?dot('H')+dot('O')+dot('H'):dot('O')+dot('O')}</span>`;
const many=(kind,n=5,hi=false)=>`<div class="microscope">${Array.from({length:n},(_,i)=>molecule(kind,hi&&i===0)).join('')}</div>`;
const iron=(n=15)=>`<div class="microscope"><div class="iron-grid">${Array.from({length:n},()=>dot('Fe')).join('')}</div></div>`;
const choice=(field,value,label)=>`<button type="button" data-action="choose" data-field="${field}" data-value="${value}" class="${state[field]===value?'selected':''}" aria-pressed="${state[field]===value}">${label}</button>`;
function first(){return `<div class="stage-head"><div><span class="badge">第 1 关 · 放大水</span><h2>一组水分子里有什么？</h2></div></div><p class="task">打开微观模型，再点开一组水分子的组成。</p><div class="workbench"><div class="display"><h3>${state.zoom?'微观模型 · 分组观察':'肉眼视野 · 一杯纯水'}</h3><div class="window">${state.zoom?many('water',5,state.inspected):'<div class="surface" aria-label="一杯纯水"></div>'}</div><div class="caption">${state.inspected?'黄框是一组水分子：里面有 2 个氢原子、1 个氧原子。':state.zoom?'每个边框圈住一组水分子；点开一组，查看原子。':'肉眼看不到分子。请切换到教学用微观模型。'}</div></div><div class="tools"><h3>观察工具</h3><button type="button" data-action="zoom">${state.zoom?'🔍 回到肉眼':'🔍 打开微观模型'}</button><button type="button" data-action="inspect" ${state.zoom?'':'disabled'}>👆 点开一组水分子的组成</button><p class="mini">“点开”只是在图中标出内部原子，不是让水分子发生分解。</p><h3>这一组整体叫</h3><div class="options">${choice('answer','molecule','水分子')}${choice('answer','atom','一个原子')}</div></div></div>`}
function second(){const isIron=state.sample==='iron';return `<div class="stage-head"><div><span class="badge">第 2 关 · 比一比</span><h2>物质都由分子构成吗？</h2></div></div><p class="task">依次看氧气和铁的模型，分别判断组成它们的微粒。</p><div class="workbench"><div class="display"><h3>${isIron?'铁块 · 铁原子模型':'氧气 · 氧分子模型'}</h3><div class="window">${state.zoom?(isIron?iron():many('oxygen')):`<div class="macro ${isIron?'metal':'gas'}" aria-label="${isIron?'铁块':'氧气容器'}">${isIron?'铁 Fe':'氧气 O₂'}</div>`}</div><div class="caption">${state.zoom?(isIron?'排列中的 Fe 各代表一个铁原子；这里不画独立的铁分子。':'每个边框圈住 2 个氧原子，代表一个氧分子 O₂。'):'肉眼模型无法分辨微粒；点击微观模型观察。'}</div></div><div class="tools"><h3>切换样品</h3><div class="switches"><button type="button" data-action="sample" data-id="oxygen" class="${!isIron?'selected':''}">氧气 O₂</button><button type="button" data-action="sample" data-id="iron" class="${isIron?'selected':''}">铁 Fe</button></div><button type="button" data-action="zoom">${state.zoom?'🔍 回到肉眼':'🔍 打开微观模型'}</button><p class="mini">已查看：氧气 ${state.seen.oxygen?'✓':'○'}　铁 ${state.seen.iron?'✓':'○'}</p><h3>氧气由什么微粒构成？</h3><div class="options">${choice('oxygen','molecule','分子')}${choice('oxygen','atom','原子')}</div><h3>金属铁由什么微粒构成？</h3><div class="options">${choice('iron','molecule','分子')}${choice('iron','atom','原子')}</div></div></div>`}
const mysteries=[['A','water','H、O 组合成一组'],['B','oxygen','O、O 组合成一组'],['C','iron','Fe 排列，没有分组']];
function third(){return `<div class="stage-head"><div><span class="badge">第 3 关 · 自己辨认</span><h2>微观图像归档</h2></div></div><p class="task">点选 A、B、C 中一张微观图，再点下面的归档格。可重新归档。</p><div class="mysteries">${mysteries.map(([id,kind,note])=>`<button type="button" class="mystery ${state.selected===id?'selected':''}" data-action="select" data-id="${id}" aria-pressed="${state.selected===id}"><div class="microscope" aria-hidden="true">${kind==='iron'?'<div class="iron-grid">'+Array.from({length:9},()=>dot('Fe')).join('')+'</div>':Array.from({length:2},()=>molecule(kind)).join('')}</div><span><strong>样品 ${id}</strong><small>${note}</small><small>${state.placed[id]?'已归档 ↗':'点我'}</small></span></button>`).join('')}</div><div class="destinations"><button type="button" class="destination" data-action="place" data-id="molecule">由分子构成<span class="placed">${mysteries.filter(x=>state.placed[x[0]]==='molecule').map(x=>x[0]).join('、')||'等待样品…'}</span></button><button type="button" class="destination" data-action="place" data-id="atom">由原子构成<span class="placed">${mysteries.filter(x=>state.placed[x[0]]==='atom').map(x=>x[0]).join('、')||'等待样品…'}</span></button></div><p class="task">${state.selected?'已选中样品 '+state.selected+'，现在点归档格。':'先找出是否有“一组一组”的分子模型。'}</p>`}
function summary(){return `<div class="stage-head"><span class="badge">本轮完成</span><h2>能认出分子和原子了！</h2></div><div class="summary"><ol><li>水可由水分子构成，水分子由氢、氧原子组成。</li><li>氧气由氧分子构成，每组氧分子含两个氧原子。</li><li>铁由铁原子构成；并非所有物质都由分子构成。</li></ol><p>${Object.keys(evidence.mistakes).length?'复习建议：回到第 '+Object.keys(evidence.mistakes).join('、')+' 关，重新观察分组。':'试着向家人解释：分子和原子在图里各是哪一层？'}</p></div><p class="task">记录只保存在当前浏览器的学习者档案。</p>`}
function render(){$('#learner').value=learner;$('#steps').innerHTML=[0,1,2].map(i=>`<span class="${i<stage?'done':i===stage?'active':''}"></span>`).join('');$('#lab').innerHTML=[first,second,third,summary][stage]();$('#feedback').textContent=message;$('#feedback').className='feedback '+tone;$('#back').disabled=stage===0;$('#verify').hidden=stage===3;$('#next').hidden=!passed&&stage!==3;$('#next').textContent=stage===3?'返回知识地图 →':'下一关 →'}
function change(){passed=false;message='';tone='';render()}
function fail(reason){errors++;evidence.mistakes[stage+1]=(evidence.mistakes[stage+1]||0)+1;if(errors>=2){evidence.hints++;reason+=' 提示：'+['黄框圈住整个水分子，里面的 H、O 小球是原子。','氧气图有一组一组 O₂；铁图是 Fe 原子排列。','A、B 有边框分组；C 是未分组的铁原子。'][stage]}message=reason;tone='bad';persist();render()}
function verify(){if(stage===0){if(!state.zoom||!state.inspected)return fail('先打开微观模型，并点开一组水分子的组成。');if(state.answer!=='molecule')return fail('一整组 H—O—H 是水分子，里面的 H 与 O 才是原子。');passed=true;message='正确：水分子是一组整体，内部由原子构成。';tone='good'}else if(stage===1){if(!state.seen.oxygen||!state.seen.iron)return fail('两个样品都要打开微观模型查看。');if(state.oxygen!=='molecule'||state.iron!=='atom')return fail('氧气图是一组组氧分子，铁图是排列的铁原子。');passed=true;message='发现了：有的物质由分子构成，有的由原子构成。';tone='good'}else if(stage===2){if(mysteries.some(([id])=>!state.placed[id]))return fail('请将 A、B、C 三张图都归档。');if(state.placed.A!=='molecule'||state.placed.B!=='molecule'||state.placed.C!=='atom')return fail('请看边框是否圈成一组：A、B 是分子组，C 是原子排列。');passed=true;message='三个样品都归对了！分子内部仍由原子组成。';tone='good'}render()}
function move(n){stage=n;init();persist();render()}
$('#switch').onclick=()=>{learner=$('#learner').value.trim()||'学习者一';localStorage.setItem('learning-lab:learner',learner);saved=read();stage=Math.max(0,Math.min(3,Number(saved.stage)||0));evidence=saved.evidence||{mistakes:{},hints:0};init();render()};$('#learner').addEventListener('change',()=>$('#switch').click());$('#reset').onclick=()=>{localStorage.removeItem(key());evidence={mistakes:{},hints:0};move(0)};$('#back').onclick=()=>{if(stage>0)move(stage-1)};$('#verify').onclick=verify;$('#next').onclick=()=>{if(stage===3){location.href='../index.html';return}if(passed)move(stage+1)};
$('#lab').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='zoom'&&stage<2){state.zoom=!state.zoom;if(state.zoom&&stage===1)state.seen[state.sample]=true;change()}else if(a==='inspect'&&stage===0&&state.zoom){state.inspected=true;change()}else if(a==='sample'&&stage===1){state.sample=b.dataset.id;if(state.zoom)state.seen[state.sample]=true;change()}else if(a==='choose'){state[b.dataset.field]=b.dataset.value;change()}else if(a==='select'&&stage===2){state.selected=b.dataset.id;change()}else if(a==='place'&&stage===2){if(state.selected){state.placed[state.selected]=b.dataset.id;state.selected=null;change()}else{message='先点选一张微观图，再点归档格。';tone='bad';render()}}});init();render()})();
