(()=>{'use strict';
const lessons={
ce03:{title:'质量守恒定律与反应前后质量',stages:[
{heading:'密闭容器里的总质量',task:'点击“让反应发生”，看气体仍留在密闭容器内。',kind:'closed',buttons:[['react','让反应发生']],need:['react'],question:'为什么天平仍显示 100 g？',answers:['生成的 8 g 气体也在密闭系统内','反应没有发生，物质没有改变'],correct:0,tip:'看容器内的溶液与气体：92 + 8 = 100 g。'},
{heading:'打开盖子后天平变轻？',task:'点击“打开盖子”，看气体去了哪里；再点“算上逸出气体”。',kind:'open',buttons:[['open','打开盖子'],['count','算上逸出气体']],need:['open','count'],question:'为什么读数变成 92 g，但总质量仍守恒？',answers:['8 g 气体离开了天平上的容器；合计仍是 100 g','反应消灭了 8 g 物质'],correct:0,tip:'称量范围变了：92 g 在容器中，8 g 已逸出。'}]},
ce04:{title:'化学方程式的书写、条件和符号',stages:[
{heading:'把文字反应写成方程式',task:'依次点“写反应物”“写生成物”“标注点燃”，看箭头两侧的意思。',kind:'write',buttons:[['left','写反应物'],['right','写生成物'],['condition','标注点燃']],need:['left','right','condition'],question:'箭头和“点燃”分别表示什么？',answers:['箭头指向生成物；点燃写在箭头上方表示反应条件','箭头表示等于号；点燃是一种生成物'],correct:0,tip:'化学式与系数表示物质和数量；条件不写进化学式。'},
{heading:'气体符号放在哪里？',task:'点击“生成气泡”，再给生成的 CO₂ 标注 ↑。',kind:'gas',buttons:[['bubbles','生成气泡'],['up','给 CO₂ 标注 ↑']],need:['bubbles','up'],question:'这里的 ↑ 有何作用？',answers:['标出从溶液中生成并逸出的气体','表示氧气作为反应物向上飞'],correct:0,tip:'示例：CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂↑；↑ 是产物气体的标记。'}]},
ce05:{title:'系数与下标：守恒配平练习',stages:[
{heading:'镁与氧气：只改系数',task:'调整三处系数，配平 Mg + O₂ → MgO。',kind:'balance',formula:['Mg','O₂','MgO'],atoms:[[1,0],[0,2],[1,1]],target:[2,1,2],need:['balanced'],question:'为什么 O₂ 的下标 ₂ 不能改？',answers:['改下标会改变物质；只在化学式前加系数','下标和系数是同一种数字'],correct:0,tip:'目标：2Mg + O₂ → 2MgO。逐行比较 Mg 和 O。'},
{heading:'铁与氧气：迁移练习',task:'调整系数，配平 Fe + O₂ → Fe₃O₄。',kind:'balance',formula:['Fe','O₂','Fe₃O₄'],atoms:[[1,0],[0,2],[3,4]],target:[3,2,1],need:['balanced'],question:'配平后左右 Fe、O 分别多少？',answers:['Fe 3 个、O 4 个，两侧相同','Fe 1 个、O 2 个，两侧相同'],correct:0,tip:'右侧 Fe₃O₄ 已有 3 Fe、4 O；左边试 3Fe 与 2O₂。'}]},
ce06:{title:'基本反应类型与反应条件',stages:[
{heading:'谁替换了谁？',task:'点击“让锌替换氢”，看 Zn 与 H 的位置变化。',kind:'replace',buttons:[['replace','让锌替换氢']],need:['replace'],question:'Zn + 2HCl → ZnCl₂ + H₂ 属于？',answers:['置换反应：一种单质与一种化合物生成新单质和新化合物','化合反应：所有粒子合成一种物质'],correct:0,tip:'Zn 是锌，HCl 是盐酸中的氯化氢；示意图只对照组成，不指导实际实验。'},
{heading:'条件和反应类型是两件事',task:'点“加热条件”再点“分解模型”，比较反应前后物质数。',kind:'heat',buttons:[['heat','加热条件'],['break','分解模型']],need:['heat','break'],question:'CaCO₃ → CaO + CO₂ 属于什么类型？',answers:['分解反应；加热是该示例的反应条件','加热反应；加热就是第五种基本反应类型'],correct:0,tip:'CaCO₃ 是碳酸钙，CaO 是氧化钙，CO₂ 是二氧化碳。一个反应物生成两种产物。'}]},
ce07:{title:'利用化学方程式进行简单计算',stages:[
{heading:'先看质量比例',task:'点“投入 12 g 碳”和“配足 32 g 氧气”，观察得到 44 g 二氧化碳。',kind:'mass',buttons:[['carbon','投入 12 g 碳'],['oxygen','配足 32 g 氧气']],need:['carbon','oxygen'],question:'C + O₂ → CO₂ 中 12:32:44 表示什么？',answers:['这组充分反应的质量比例；12 + 32 = 44','系数是 12:32:44，必须写在方程式前'],correct:0,tip:'相对质量 C=12，O₂=32，CO₂=44；单位是 g 的具体倍数。'},
{heading:'把所有质量放大两倍',task:'点击“碳变 24 g”和“氧气变 64 g”，观察产物空格并填写质量。',kind:'scale',buttons:[['carbon','碳变 24 g'],['oxygen','氧气变 64 g']],need:['carbon','oxygen','value'],question:'为什么答案是 88 g？',answers:['质量比例同步乘 2；24 + 64 = 88','只把碳加倍，氧气量无需改变'],correct:0,tip:'12:32:44 整体乘 2 得 24:64:88；本题假设反应充分且无其他反应。'}]}
};
const id=document.body.dataset.id,lesson=lessons[id],$=q=>document.querySelector(q);if(!lesson)return;let page=0,state,selected,passed,failures;const current=()=>lesson.stages[page],has=k=>!!state[k],tile=(label,color='')=>`<span class="eq-tile ${color}">${label}</span>`;function reset(){state={coeff:[1,1,1],changed:false,value:''};selected=-1;passed=false;failures=0;$('#feedback').textContent='';render()}function source(){let c=current(),k=c.kind;if(k==='closed'||k==='open'){let open=k==='open'&&has('open'),react=k==='closed'?has('react'):true;return `<div class="mass-vessel ${open?'opened':''}"><b>${open?'开口':'密闭'}容器</b><div>${react?'溶液 92 g':'反应物 100 g'}</div>${react&&!open?tile('气体 8 g','gas'):''}</div>${open?tile('逸出气体 8 g →','gas'):''}<div class="mass-scale">天平读数 <strong>${open?'92':'100'} g</strong></div><div class="eq-note">${open?(has('count')?'容器 92 g + 逸出 8 g = 系统总量 100 g':'8 g 气体已离开天平'):react?'92 + 8 = 100 g':'反应前总质量 100 g'}</div>`}
if(k==='write')return `<div class="eq-line">${has('left')?tile('2H₂ + O₂','reactant'):tile('反应物 ?')}<span class="eq-arrow">${has('condition')?'<small>点燃</small>':''}→</span>${has('right')?tile('2H₂O','product'):tile('生成物 ?')}</div><div class="eq-note">${has('right')?'H4、O2 → H4、O2；条件不是产物':'H₂ 是氢气，O₂ 是氧气，H₂O 是水。'}</div>`;
if(k==='gas')return `<div class="eq-line">${tile('溶液中的反应物','reactant')}<span class="eq-arrow">→</span>${tile(has('bubbles')?`CaCl₂ + H₂O + CO₂${has('up')?'↑':''}`:'生成物 ?','product')}</div><div class="eq-bubbles">${has('bubbles')?'○ ○ ○　CO₂ 气泡示意':'等待观察气体'}</div><div class="eq-note">CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂${has('up')?'↑':''}</div>`;
if(k==='balance'){let a=c.atoms,v=state.coeff,l0=a[0][0]*v[0]+a[1][0]*v[1],l1=a[0][1]*v[0]+a[1][1]*v[1],r0=a[2][0]*v[2],r1=a[2][1]*v[2],names=id==='ce05'?(page?'Fe':'Mg'):'A';return `<div class="coefficient-row">${c.formula.map((f,i)=>`<div class="coefficient"><button data-index="${i}" data-delta="-1" aria-label="减少${f}系数">−</button><b>${v[i]} ${f}</b><button data-index="${i}" data-delta="1" aria-label="增加${f}系数">＋</button></div>${i===0?'<strong>＋</strong>':i===1?'<strong>→</strong>':''}`).join('')}</div><div class="atom-ledger"><span>${names}：左 ${l0} / 右 ${r0} ${l0===r0?'✓':'≠'}</span><span>O：左 ${l1} / 右 ${r1} ${l1===r1?'✓':'≠'}</span></div><div class="eq-note">只能改前面的系数，化学式中的下标固定。</div>`}
if(k==='replace')return `<div class="eq-line">${tile('Zn','reactant')} + ${tile('H—Cl × 2','reactant')} <span class="eq-arrow">→</span> ${has('replace')?`${tile('Cl—Zn—Cl','product')} + ${tile('H—H','gas')}`:tile('待替换')}</div><div class="eq-note">${has('replace')?'Zn 与 Cl 结合；两个 H 组成 H₂。':'单质 + 化合物 → 新单质 + 新化合物'}</div>`;
if(k==='heat')return `<div class="eq-line">${tile('CaCO₃','reactant')}<span class="eq-arrow">${has('heat')?'<small>高温</small>':''}→</span>${has('break')?`${tile('CaO','product')} + ${tile('CO₂','gas')}`:tile('待生成')}</div><div class="eq-note">${has('break')?'一种反应物 → 两种产物；Ca1 C1 O3 两侧相等':'高温是该示例的反应条件，不是反应类型。'}</div>`;
if(k==='mass'||k==='scale'){let n=k==='scale'?2:1,x=has('carbon'),y=has('oxygen');return `<div class="mass-bars"><div><b>碳 C</b><span class="bar carbon" style="width:${x?40*n:8}%"></span><strong>${x?12*n:'?'} g</strong></div><div><b>氧气 O₂</b><span class="bar oxygen" style="width:${y?40*n:8}%"></span><strong>${y?32*n:'?'} g</strong></div><div><b>二氧化碳 CO₂</b><span class="bar product" style="width:${x&&y?40*n:8}%"></span><strong>${x&&y?(k==='scale'?'待填写':44):'?'} g</strong></div></div><div class="eq-note">${k==='scale'?'质量比例 12:32:44 → 24:64:?':'C + O₂ → CO₂；12 + 32 = 44（g）'}</div>`}
return ''}
function ready(){let c=current();return c.kind==='balance'?state.changed&&state.coeff.every((x,i)=>x===c.target[i]):c.need.every(k=>k==='value'?state.value==='88':has(k))}
function render(){let end=page===lesson.stages.length;$('#progress').textContent=end?'完成':`第 ${page+1}/${lesson.stages.length} 关`;$('#lesson').innerHTML=end?`<h2>完成：${lesson.title}</h2><p>你已动手调整模型，并解释观察结果。</p><a class="eq-home" href="../index.html">返回知识地图 →</a>`:`<h2>${current().heading}</h2><p class="instruction">${current().task}</p><div class="workbench"><section><h3>观察模型</h3><div class="eq-scene">${source()}</div></section><section><h3>动手改变画面</h3><div class="eq-actions">${(current().buttons||[]).map(([key,label])=>`<button data-act="${key}" ${key==='up'&&!has('bubbles')||key==='break'&&!has('heat')?'disabled':''}>${label}</button>`).join('')}</div>${current().kind==='scale'?'<label class="mass-input">生成 CO₂ 的质量（g）<input id="mass-answer" type="number" inputmode="numeric" min="0" max="999" value="'+state.value+'" placeholder="填写质量"></label>':''}<h3>观察后判断</h3><p>${current().question}</p><div class="eq-choices">${current().answers.map((a,i)=>`<button data-choice="${i}" aria-pressed="${selected===i}">${a}</button>`).join('')}</div></section></div>`;$('#back').disabled=page===0;$('#check').hidden=end;$('#next').hidden=end||!passed;$('#feedback').className=passed?'feedback good':'feedback'}
$('#lesson').addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.choice!==undefined){selected=+b.dataset.choice;render();return}if(b.dataset.index!==undefined){let i=+b.dataset.index;state.coeff[i]=Math.max(1,Math.min(5,state.coeff[i]+Number(b.dataset.delta)));state.changed=true}else if(b.dataset.act)state[b.dataset.act]=true;else return;passed=false;$('#feedback').textContent='';render()});$('#lesson').addEventListener('input',e=>{if(e.target.id==='mass-answer'){state.value=e.target.value;passed=false;$('#next').hidden=true}});
$('#check').onclick=()=>{if(!ready()){$('#feedback').textContent='先完成模型操作。提示：'+current().tip;return}if(selected!==current().correct){failures++;$('#feedback').textContent='判断还不对。'+current().tip;return}passed=true;$('#feedback').textContent='正确。'+(page===lesson.stages.length-1?'本课完成。':'继续下一关。');render()};$('#next').onclick=()=>{if(passed){page++;reset()}};$('#back').onclick=()=>{if(page){page--;reset()}};$('#restart').onclick=()=>{page=0;reset()};reset();
})();
