(()=>{'use strict';const $=s=>document.querySelector(s),id=document.body.dataset.id;
const labs={
'cb03-05':{title:'相对分子质量与元素质量比',stages:[
{kind:'mass',heading:'拼出 H₂O 的相对分子质量',task:'加 2 个 H、1 个 O，比较各元素的质量贡献。',atoms:['H','O'],target:{H:2,O:1},formula:'H₂O',choices:[['18','相对分子质量 18'],['17','相对分子质量 17'],['16','相对分子质量 16']],correct:'18',tip:'H 相对原子质量约 1，O 约 16；2×1+16=18，氢与氧的质量比 2:16=1:8。'},
{kind:'mass',heading:'拼出 CO₂ 的质量比',task:'加 1 个 C、2 个 O，观察元素质量贡献。',atoms:['C','O'],target:{C:1,O:2},formula:'CO₂',choices:[['3:8','碳:氧 = 3:8'],['1:2','碳:氧 = 1:2'],['12:16','碳:氧 = 12:16']],correct:'3:8',tip:'C 约 12，O 约 16；CO₂ 总相对分子质量 44，碳:氧质量比 12:32=3:8。'}]},
'cb03-06':{title:'化合物中元素质量分数',stages:[
{kind:'mass',heading:'水中氧的质量分数',task:'加 2 个 H、1 个 O，看氧占总质量的比例。',atoms:['H','O'],target:{H:2,O:1},formula:'H₂O',choices:[['88.9%','氧约占 88.9%'],['50%','氧占 50%'],['11.1%','氧约占 11.1%']],correct:'88.9%',tip:'质量分数按质量算：水中氧约 16÷18×100%≈88.9%，不能按 1/3 个原子计算。'},
{kind:'mass',heading:'二氧化碳中碳的质量分数',task:'加 1 个 C、2 个 O，观察碳占总质量的比例。',atoms:['C','O'],target:{C:1,O:2},formula:'CO₂',choices:[['27.3%','碳约占 27.3%'],['33.3%','碳占 33.3%'],['72.7%','碳约占 72.7%']],correct:'27.3%',tip:'CO₂ 中碳的质量分数约 12÷44×100%≈27.3%；下标表示原子个数，不是质量份数。'}]},
'cp01-01':{title:'空气的组成与空气质量',stages:[
{kind:'air',heading:'观察干燥空气的气体组成',task:'点“显示干燥空气”，看 100 格示意的主要气体。',mode:'clean',choices:[['氮气','氮气约占 78%，氧气约占 21%'],['氧气','氧气约占 78%'],['纯氧','空气是纯氧']],correct:'氮气',tip:'按体积，干燥空气中氮气约 78%、氧气约 21%，还有氩气等；空气是混合物。'},
{kind:'air',heading:'空气质量变化看什么？',task:'点“加入污染物示意”，观察额外的污染物标记。',mode:'polluted',choices:[['污染物','关注颗粒物、臭氧等污染物'],['氮气','只要氮气多就是污染'],['纯净','空气质量差说明没有氧气']],correct:'污染物',tip:'空气质量关注颗粒物、臭氧等污染物的浓度；本图红色标记只是示意，不代表真实监测数值。'}]},
'cp01-02':{title:'测定空气中氧气含量',stages:[
{kind:'tube',heading:'密闭空气中消耗氧气',task:'每次点“推进”消耗 7 mL 氧气，共推进 3 次。',target:21,choices:[['21','水上升约 21 mL，约占 1/5'],['79','水上升约 79 mL'],['100','全部气体都消失']],correct:'21',tip:'100 mL 干燥空气中氧气约 21 mL。密闭条件下充分消耗氧气并冷却到起始温度后，水约补入 21 mL。'},
{kind:'tube',heading:'反应不充分会怎样？',task:'只推进 2 次，模拟仅消耗 14 mL 氧气。',target:14,choices:[['偏小','测得氧气体积分数偏小'],['准确','仍然准确是 21%'],['偏大','一定偏大']],correct:'偏小',tip:'氧气未被充分消耗时，水上升少于约 21 mL，计算出的氧气比例偏小；装置也应密闭并冷却后读数。'}]},
'cp01-03':{title:'氧气的性质与用途',stages:[
{kind:'oxygen',heading:'氧气怎样影响燃烧？',task:'先点“空气”，再点“氧气较充足”，观察带火星木条示意。',mode:'rich',choices:[['助燃','氧气支持燃烧'],['可燃','氧气本身是燃料'],['灭火','氧气使燃烧停止']],correct:'助燃',tip:'氧气支持燃烧，但氧气本身不是燃料；带火星木条在氧气中可复燃。'},
{kind:'oxygen',heading:'氧气可用在哪里？',task:'点“供氧场景”，观察供氧而非燃料的作用。',mode:'supply',choices:[['供氧','医疗供氧或潜水呼吸供氧'],['燃料','将氧气当作可燃燃料'],['污染','氧气就是空气污染物']],correct:'供氧',tip:'氧气可用于供氧，也用于支持某些高温氧化过程；医疗用氧须由专业人员指导。'}]}
};
const lab=labs[id],atomic={H:1,C:12,O:16};let learner=localStorage.getItem('learning-lab:learner')||'学习者一';const key=()=>`learning-lab:v1:${learner}:${id}`;const read=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}};let saved=read(),stage=Math.max(0,Math.min(lab.stages.length,Number(saved.stage)||0)),counts={},amount=0,mode='',visited={},answer='',operated=false,feedback='',tone='',errors=saved.errors||0,hints=saved.hints||0;const spec=()=>lab.stages[Math.min(stage,lab.stages.length-1)],done=()=>stage===lab.stages.length,persist=()=>localStorage.setItem(key(),JSON.stringify({stage,errors,hints,updated:new Date().toISOString()}));
function board(){const s=spec();if(s.kind==='mass'){let total=s.atoms.reduce((n,k)=>n+(counts[k]||0)*atomic[k],0);return `<div class="formula">目标：${s.formula} · ${total?'当前原子':'先加入原子'}</div><div class="unit-row">${s.atoms.map(k=>Array.from({length:counts[k]||0},()=>`<span class="unit ${k.toLowerCase()}">${k}</span>`).join('')).join('')||'<span>从右侧添加原子</span>'}</div><div class="mass-chart">${s.atoms.map(k=>{let mass=(counts[k]||0)*atomic[k],pct=total?mass/total*100:0;return `<div class="mass-row"><span>${k} × ${counts[k]||0}</span><span class="mass-track"><span class="mass-fill" style="display:block;width:${pct}%"></span></span><b>${mass}</b></div>`}).join('')}</div><div class="meter">质量和：${total}${total?' · '+s.atoms.map(k=>`${k} ${((counts[k]||0)*atomic[k]/total*100).toFixed(1)}%`).join(' · '):''}</div><div class="guidance">相对原子质量取 H≈1、C≈12、O≈16；这里的“质量和”是相对分子质量的计算值，不带 g。</div>`}
if(s.kind==='air')return `<div class="gas-grid" aria-label="100格空气示意">${Array.from({length:100},(_,i)=>`<span class="gas-dot ${(i<78?'nitrogen':i<99?'oxygen':'other')+(s.mode==='polluted'&&mode==='polluted'&&i>=96?' pollution':'')}">${mode?i<78?'N₂':i<99?'O₂':'·':''}</span>`).join('')}</div><div class="meter">${mode==='polluted'?'污染物标记仅作示意':'78 格 N₂ · 21 格 O₂ · 1 格其他气体（约）'}</div><p class="guidance">100 格近似按体积表达干燥空气；污染物标记是叠加提示，不替代原有气体，也不表示实际浓度。</p>`;
if(s.kind==='tube')return `<div class="tube"><div class="gas" style="width:${100-amount}%">剩余气体 ${100-amount} mL</div><div class="water" style="width:${amount}%">${amount?amount+' mL':''}</div></div><div class="meter">已消耗 O₂ ${amount} mL · 水约补入 ${amount} mL</div><p class="guidance">密闭模型：初始 100 mL 干燥空气，假设充分反应后冷却回初始温度，且水补入消耗的气体体积。图形不模拟真实反应速率或仪器操作。</p>`;
return `<div class="oxygen-visual ${mode==='rich'?'rich':''}">${mode==='supply'?'<div class="supply-path"><span class="oxygen-pill">O₂</span><span class="supply-arrow">→</span><span class="breath">呼吸供氧</span></div>':`<div class="oxygen-dots">${Array.from({length:mode==='rich'?8:3},()=>'<span>O₂</span>').join('')}</div><div class="splint"><span class="ember"></span><span class="wood"></span></div>`}</div><div class="meter">${mode==='air'?'空气中 O₂ 约 21% · 木条示意未复燃':mode==='rich'?'氧气较充足 · 带火星木条复燃示意':mode==='supply'?'供氧场景 · 提供呼吸所需氧气':'选择场景观察'}</div><p class="guidance">这是概念示意，不是实际点燃或医疗操作指导；燃烧效果还取决于燃料、温度等条件。</p>`}
function controls(){const s=spec();if(s.kind==='mass')return s.atoms.map(k=>`<button data-act="add" data-val="${k}">＋ ${k}</button><button data-act="remove" data-val="${k}" ${!counts[k]?'disabled':''}>− ${k}</button>`).join('');if(s.kind==='air')return `<button data-act="mode" data-val="${s.mode}">${s.mode==='clean'?'显示干燥空气':'加入污染物示意'}</button>`;if(s.kind==='tube')return `<button data-act="advance" ${amount>=s.target?'disabled':''}>推进：消耗 7 mL O₂</button><button data-act="reverse" ${amount<=0?'disabled':''}>↶ 撤回一步</button>`;return s.mode==='rich'?'<button data-act="mode" data-val="air">空气</button><button data-act="mode" data-val="rich">氧气较充足</button>':'<button data-act="mode" data-val="supply">供氧场景</button><button data-act="mode" data-val="air">回到空气</button>'}
function ready(){const s=spec();if(s.kind==='mass')return operated&&Object.entries(s.target).every(([k,n])=>(counts[k]||0)===n);if(s.kind==='tube')return amount===s.target&&operated;if(s.kind==='oxygen'&&s.mode==='rich')return !!visited.air&&!!visited.rich;return mode===s.mode&&operated}
function render(){const s=spec();$('#learner').value=learner;$('#steps').innerHTML=lab.stages.map((_,i)=>`<span class="${i<stage?'done':''}"></span>`).join('');$('#lab').classList.toggle('completed',done());$('#lab').innerHTML=done()?`<div class="stage-head"><h2>完成：${lab.title}</h2></div><p class="task">你已操作并解释模型。可以返回知识地图继续学习。</p>`:`<div class="stage-head"><div><span class="badge">第 ${stage+1} / ${lab.stages.length} 关</span><h2>${s.heading}</h2></div></div><p class="task">${s.task}</p><div class="workbench"><div class="display"><h3>观察区</h3><div class="symbol-scene">${board()}</div></div><div class="tools"><h3>动手操作</h3><div class="control-group">${controls()}</div><h3>观察后判断</h3><div class="tiles">${s.choices.map(([v,label])=>`<button data-act="choose" data-val="${v}" aria-pressed="${answer===v}">${label}</button>`).join('')}</div><p class="explain">请先操作，再选判断并检查。</p></div></div>`;$('#feedback').textContent=feedback;$('#feedback').className='feedback '+tone;$('#back').disabled=stage===0;$('#verify').hidden=done();$('#next').hidden=!done()&&tone!=='good';$('#next').textContent=done()?'返回知识地图 →':'下一关 →'}
function fail(t){errors++;feedback=t+(errors>=2?' 提示：'+spec().tip:'');if(errors>=2)hints++;tone='bad';persist();render()}
function resetView(){counts={};amount=0;mode='';visited={};answer='';operated=false;feedback='';tone='';render()}
$('#lab').addEventListener('click',e=>{const b=e.target.closest('button[data-act]');if(!b||b.disabled)return;let act=b.dataset.act,v=b.dataset.val;if(act==='choose')answer=v;else if(act==='add'){counts[v]=(counts[v]||0)+1;operated=true}else if(act==='remove'){counts[v]=Math.max(0,(counts[v]||0)-1);operated=true}else if(act==='advance'){amount+=7;operated=true}else if(act==='reverse'){amount=Math.max(0,amount-7);operated=true}else if(act==='mode'){mode=v;visited[v]=true;operated=true}if(tone==='good')tone='';feedback='';render()});
$('#verify').onclick=()=>{if(!ready())return fail('先按任务操作，观察图形或数字变化。');if(answer!==spec().correct)return fail('再比较图中的数量与条件，选出符合观察的判断。');feedback='正确！'+spec().tip;tone='good';persist();render()};$('#next').onclick=()=>{if(done()){location.href='../index.html';return}if(tone!=='good')return;stage++;resetView();persist()};$('#back').onclick=()=>{if(stage>0){stage--;resetView();persist()}};$('#reset').onclick=()=>{localStorage.removeItem(key());stage=0;errors=0;hints=0;resetView();persist()};$('#switch').onclick=()=>{learner=$('#learner').value.trim()||'学习者一';localStorage.setItem('learning-lab:learner',learner);saved=read();stage=Math.min(lab.stages.length,Math.max(0,Number(saved.stage)||0));errors=saved.errors||0;hints=saved.hints||0;resetView()};$('#learner').addEventListener('change',()=>$('#switch').click());resetView();})();
