(()=>{'use strict';
const $=s=>document.querySelector(s), id=document.body.dataset.id, titles={'cb01-07':'宏观物质、微观粒子与符号的对应','cb01-08':'微观模型的适用范围','cb02-01':'元素、原子与单质的区别','cb02-02':'常见元素符号与读写','cb02-03':'元素周期表的基本信息'};
let learner=localStorage.getItem('learning-lab:learner')||'学习者一';const key=()=>`learning-lab:v1:${learner}:${id}`;function read(){try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}}
let stage=Math.min(2,Math.max(0,Number(read().stage)||0)), chosen='', touched=false, errors=0, hints=0, feedback='',tone='', counts={},mode='',picked='',completed=false;
const lessons={
'cb01-07':[
{title:'从一杯水走到 H₂O',task:'点“加入水分子”，观察杯中微粒怎样增加。',start:'这是一杯水的简化视图。',choices:[['H₂O','水分子符号 H₂O'],['H₂','氢分子 H₂'],['O₂','氧分子 O₂']],correct:'H₂O',tip:'一杯水含很多水分子，每个水分子由 2 个氢原子和 1 个氧原子构成；H₂O 表示这种微粒。'},
{title:'从氧气走到 O₂',task:'点“加入氧分子”，再选表达这种微粒的符号。',start:'气体中有许多分散的氧分子。',choices:[['O₂','O₂'],['O','O'],['H₂O','H₂O']],correct:'O₂',tip:'一个氧分子由 2 个氧原子构成，写 O₂；O 可以表示氧元素或一个氧原子，依上下文。'}],
'cb01-08':[
{title:'模型能告诉我们什么？',task:'切换“粒子计数”和“结构示意”，看图中哪些信息发生变化。',start:'同一杯水的两种示意方式。',choices:[['数量','能说明示意粒子数量'],['轨道','能显示真实电子运动轨道'],['温度','能直接读出水温']],correct:'数量',tip:'画出的圆球是简化符号，能帮助数粒子；圆球大小与距离不是实物比例。'},
{title:'模型不能证明什么？',task:'切换两种模型，再判断从示意图无法直接得到哪项。',start:'水分子的球棍图与简化结构图。',choices:[['距离','原子间的真实距离'],['组成','一个水分子含 2 个 H 和 1 个 O'],['连接','图示的原子连接关系']],correct:'距离',tip:'模型可表达组成和连接，不能仅凭画面的像素长度读出真实尺度或运动。'}],
'cb02-01':[
{title:'氧原子如何组成氧气？',task:'点“组成一个 O₂ 分子”，观察两个氧原子连接。',start:'两个氧原子属于同一种元素。',choices:[['单质','氧气是单质'],['元素','氧气就是一个氧元素'],['原子','一个 O₂ 分子就是一个氧原子']],correct:'单质',tip:'氧元素是一类质子数相同的原子的统称；两个氧原子组成一个 O₂ 分子，氧气是由氧元素组成的单质。'},
{title:'把不同元素放在一起',task:'点“加入氢原子”，观察模型从 O₂ 切换为 H₂O。',start:'比较单质与由不同元素组成的物质。',choices:[['化合物','水是化合物'],['单质','水是氧单质'],['元素','一个水分子是一种元素']],correct:'化合物',tip:'H₂O 分子含氢、氧两种元素的原子；水是化合物，不是单质。'}],
'cb02-02':[
{title:'拼出氢元素符号',task:'先点字母卡 H，观察符号卡的变化。',start:'元素符号第一个字母大写。',choices:[['H','H'],['h','h'],['He','He']],correct:'H',tip:'氢的符号是 H；大小写不能互换。'},
{title:'拼出氦元素符号',task:'依次点 H 与 e，观察组合成的符号。',start:'两字母元素符号：首字母大写，第二个小写。',choices:[['He','He'],['HE','HE'],['H','H']],correct:'He',tip:'氦写 He；HE 中第二个字母大写，是错误写法。'}],
'cb02-03':[
{title:'读取元素格',task:'点元素格“氧 O”，观察原子序数与符号。',start:'周期表元素格展示名称、符号、原子序数。',choices:[['8','氧的原子序数是 8'],['16','氧的原子序数是 16'],['O₂','氧的元素符号是 O₂']],correct:'8',tip:'氧的原子序数为 8，元素符号 O；O₂ 是氧分子符号。'},
{title:'对比同一周期',task:'点“钠 Na”和“镁 Mg”，观察序数与所在行。',start:'横行叫周期，纵列叫族。',choices:[['同周期','钠和镁同属第 3 周期'],['同族','钠和镁在同一族'],['同序数','两者原子序数相同']],correct:'同周期',tip:'钠 11 与镁 12 位于第 3 周期相邻位置，不属于同一族。'}]
};
const particle=(s)=>`<span class="particle ${s.toLowerCase()}">${s}</span>`;
function visual(){const n=counts.n||0;if(id==='cb01-07'){let mol=stage===0?`${particle('H')}${particle('O')}${particle('H')}`:`${particle('O')}${particle('O')}`;return `<div class="particles">${Array.from({length:Math.min(n,4)},()=>`<span class="molecule">${mol}</span>`).join('')||'<span>空视窗 · 点击添加微粒</span>'}</div><div class="stat">${n} 个${stage===0?'水':'氧'}分子（示意）</div>`}
if(id==='cb01-08')return `<div class="visual-label">${mode==='structure'?'球棍结构示意：H — O — H':'粒子计数示意：两个水分子'}</div><div class="particles">${(mode==='structure'?1:2)===1?`<span class="molecule">${particle('H')}${particle('O')}${particle('H')}</span>`:Array.from({length:2},()=>`<span class="molecule">${particle('H')}${particle('O')}${particle('H')}</span>`).join('')}</div><span class="visual-label">图形并非真实比例，也不呈现电子运动</span>`;
if(id==='cb02-01')return `<div class="particles">${!touched?`${particle('O')} ${stage?'　→　':''} ${particle('O')}`:stage===0?`<span class="molecule">${particle('O')}${particle('O')}</span>`:`<span class="molecule">${particle('H')}${particle('O')}${particle('H')}</span>`}</div><div class="stat">${!touched?'分开的原子':stage===0?'O₂ · 氧气的分子':'H₂O · 水分子'}</div>`;
if(id==='cb02-02')return `<div class="stat" aria-live="polite">正在拼写：${picked||'（空）'}</div><div class="model"><span class="nucleus">${stage===0?'氢':'氦'}</span></div>`;
return `<div class="table-wrap"><div class="periodic">${[['H',1,'氢',1,1],['He',2,'氦',1,8],['Li',3,'锂',2,1],['Be',4,'铍',2,2],['B',5,'硼',2,3],['C',6,'碳',2,4],['N',7,'氮',2,5],['O',8,'氧',2,6],['F',9,'氟',2,7],['Ne',10,'氖',2,8],['Na',11,'钠',3,1],['Mg',12,'镁',3,2]].map(([s,num,zh,row,col])=>`<button type="button" data-act="element" data-val="${s}" aria-pressed="${picked===s}" style="grid-row:${row};grid-column:${col}"><small>${num}</small><b>${s}</b>${zh}</button>`).join('')}</div></div><div class="stat">${picked?({'O':'氧 O · 原子序数 8 · 第 2 周期','Na':'钠 Na · 原子序数 11 · 第 3 周期','Mg':'镁 Mg · 原子序数 12 · 第 3 周期'}[picked]||picked+' · 点击其他元素继续比较'):'选择元素格，查看信息'}</div>`}
function actions(){if(id==='cb01-07')return `<button data-act="add">＋ 加入${stage===0?'水':'氧'}分子</button><button data-act="remove" ${!counts.n?'disabled':''}>− 移走一个</button>`;if(id==='cb01-08')return `<button data-act="model" data-val="count" aria-pressed="${mode==='count'}">粒子计数</button><button data-act="model" data-val="structure" aria-pressed="${mode==='structure'}">结构示意</button>`;if(id==='cb02-01')return `<button data-act="form">${stage===0?'组成一个 O₂ 分子':'加入氢原子，形成 H₂O'}</button><button data-act="undo" ${!touched?'disabled':''}>↶ 分开重来</button>`;if(id==='cb02-02')return `<button data-act="letter" data-val="H">H</button><button data-act="letter" data-val="e">e</button><button data-act="letter" data-val="h">h</button><button data-act="letter" data-val="E">E</button><button data-act="undo" ${!picked?'disabled':''}>↶ 删除末尾字母</button>`;return '<p class="explain">先在左侧点元素格，再做判断。可多点几个元素比较。</p>'}
function validOperation(){if(id==='cb01-07')return counts.n>0;if(id==='cb01-08')return touched;if(id==='cb02-01')return touched;if(id==='cb02-02')return picked===(stage===0?'H':'He');return stage===0?picked==='O':counts.Na&&counts.Mg}
function save(){localStorage.setItem(key(),JSON.stringify({stage,mistakes:errors,hints,updated:new Date().toISOString()}))}
function render(){const l=lessons[id][stage];$('#learner').value=learner;$('#steps').innerHTML=`<span class="${stage>0?'done':''}"></span><span class="${completed?'done':''}"></span>`;$('#lab').innerHTML=completed?`<div class="stage-head"><h2>完成：${titles[id]}</h2></div><p class="task">你已经操作了模型，也解释了变化。可以重做，或返回知识地图继续下一课。</p>`:`<div class="stage-head"><div><span class="badge">第 ${stage+1} 关 · 动手观察</span><h2>${l.title}</h2></div></div><p class="task">${l.task}</p><div class="workbench"><div class="display"><h3>可操作模型</h3><div class="scene">${visual()}</div><p class="mini">${l.start}</p></div><div class="tools"><h3>动手改变画面</h3><div class="controls">${actions()}</div><h3>观察后判断</h3><div class="tiles">${l.choices.map(([v,label])=>`<button data-act="choose" data-val="${v}" aria-pressed="${chosen===v}">${label}</button>`).join('')}</div><p class="explain">完成操作后选一个判断，再点“检查”。</p></div></div>`;$('#feedback').textContent=feedback;$('#feedback').className='feedback '+tone;$('#back').disabled=stage===0&&!completed;$('#verify').hidden=completed;$('#next').hidden=!completed&&tone!=='good';$('#next').textContent=completed?'返回知识地图 →':'下一关 →'}
function fail(s){errors++;feedback=s+(errors>=2?' 提示：'+lessons[id][stage].tip:'');if(errors>=2)hints++;tone='bad';save();render()}
function resetView(){chosen='';touched=false;feedback='';tone='';counts={};mode='count';picked='';render()}
$('#lab').addEventListener('click',e=>{const b=e.target.closest('button[data-act]');if(!b||b.disabled)return;const a=b.dataset.act,v=b.dataset.val;if(a==='choose')chosen=v;else if(a==='add'){counts.n=(counts.n||0)+1;touched=true}else if(a==='remove'){counts.n=Math.max(0,(counts.n||0)-1);touched=true}else if(a==='model'){mode=v;touched=true}else if(a==='form'){touched=true}else if(a==='undo'){if(id==='cb02-02')picked=picked.slice(0,-1);else touched=false}else if(a==='letter'){picked+=v;touched=true}else if(a==='element'){picked=v;touched=true;counts[v]=true}if(tone==='good')tone='';feedback='';render()});
$('#verify').onclick=()=>{if(!validOperation())return fail(id==='cb02-02'?'先在字母卡上拼出正确符号，注意大小写。':'先按照第一步操作模型，并观察画面变化。');if(chosen!==lessons[id][stage].correct)return fail('还不对。'+(errors?' 请比较图中粒子、符号或元素格，再选。':' 请观察变化后再试一次。'));feedback='正确！'+lessons[id][stage].tip;tone='good';save();render()};
$('#next').onclick=()=>{if(completed){location.href='../index.html';return}if(tone!=='good')return;if(stage===0){stage=1;resetView();save()}else{completed=true;stage=2;save();render()}};
$('#back').onclick=()=>{if(completed){completed=false;stage=1}else if(stage>0)stage--;resetView();save()};$('#reset').onclick=()=>{localStorage.removeItem(key());stage=0;completed=false;errors=0;hints=0;resetView();save()};$('#switch').onclick=()=>{learner=$('#learner').value.trim()||'学习者一';localStorage.setItem('learning-lab:learner',learner);const s=read();stage=Math.min(2,Math.max(0,Number(s.stage)||0));completed=stage===2;errors=s.mistakes||0;hints=s.hints||0;resetView()};$('#learner').addEventListener('change',()=>$('#switch').click());completed=stage===2;resetView();
})();
