(()=>{'use strict';
const lessons={
'cp02-03':{title:'硬水、软水与水资源保护',intro:'把同样的肥皂加入两杯水，再试一次软化示意。',stages:[{title:'相同肥皂，泡沫一样吗？',instruction:'依次点击两杯“加入肥皂”，比较泡沫。',type:'soap',actions:[['hard','硬水＋肥皂'],['soft','软水＋肥皂']],need:['hard','soft'],question:'哪杯更容易起泡？',options:['软水；硬水中的钙镁离子影响起泡','硬水；矿物质越多泡沫越多'],correct:0,hint:'看两杯泡沫的高度。硬水和软水的区别与溶解的钙、镁离子有关。'}, {title:'软化与保护水资源',instruction:'点“加热煮沸示意”，再观察硬度变化。',type:'boil',actions:[['boil','加热煮沸示意']],need:['boil'],question:'这个方法与节水的合理结论是？',options:['煮沸可降低部分暂时硬度；节约用水并防止污染','所有硬水煮沸后都是纯水，可随意浪费'],correct:0,hint:'煮沸只对某些硬度成分有效，不等于纯水。'}]},
'cp02-04':{title:'氢气的性质、燃烧与安全',intro:'先比较氢气与空气的性质，再用粒子模型看燃烧产物。',stages:[{title:'氢气会向哪里移动？',instruction:'点“释放氢气模型”，观察上升趋势。',type:'rise',actions:[['rise','释放氢气模型']],need:['rise'],question:'观察支持什么判断？',options:['氢气密度比空气小；可燃，混入空气点燃有危险','氢气比空气重，可以自行点燃检验'],correct:0,hint:'模型中气球向上。氢气与空气混合后的点燃风险必须由教师讲解。'}, {title:'燃烧后原子去了哪里？',instruction:'先加入两份 H₂，再加入一份 O₂，点“重组”。',type:'burn',actions:[['h','＋ H₂'],['o','＋ O₂'],['react','重组为水']],need:['react'],question:'2H₂ + O₂ → 2H₂O 表示什么？',options:['生成水，H4 和 O2 原子数守恒','氢原子变成氧原子'],correct:0,hint:'数左右两侧 H、O 原子；这是虚拟粒子图，不是点火步骤。'}]},
'cp02-05':{title:'蒸发、结晶与混合物分离',intro:'从盐水里分别追踪盐和水的去向。',stages:[{title:'过滤能留下溶解的盐吗？',instruction:'点击“普通滤纸”，看滤液里还有什么。',type:'filter',actions:[['filter','经过普通滤纸']],need:['filter'],question:'盐水经过普通滤纸后？',options:['溶解的盐仍在滤液中','盐全部留在滤纸上'],correct:0,hint:'普通滤纸主要截留不溶固体，盐已溶解。'}, {title:'水蒸发以后留下什么？',instruction:'连续点“温和蒸发”两次，观察盐析出。',type:'evaporate',actions:[['evaporate','温和蒸发']],need:['evaporated'],question:'想同时回收水，还需要？',options:['冷凝收集水蒸气（蒸馏思想）','继续普通过滤即可得到纯水'],correct:0,hint:'蒸发可留下盐；要收集水须让蒸气冷凝。图示不提供真实加热操作。'}]},
'ce01':{title:'原子去哪了：氢气燃烧微观模型',intro:'让氢、氧分子重新组合，亲眼数清反应前后的原子。',stages:[{title:'先放入反应物',instruction:'添加两份 H₂ 与一份 O₂，观察 H 和 O 数量。',type:'atoms',actions:[['h','＋ H₂'],['o','＋ O₂'],['react','重组']],need:['react'],question:'生成水时原子发生了什么？',options:['H 和 O 原子重新组合，种类和总数不变','氧原子消失了'],correct:0,hint:'反应前 H4 O2，反应后两份 H₂O 仍是 H4 O2。'}, {title:'反过来检查',instruction:'点“撤回重组”，再点“重新组合”，比较两侧。',type:'reverse',actions:[['undo','撤回重组'],['again','重新组合']],need:['undo','again'],question:'撤回在模型中说明什么？',options:['可以对照两侧粒子数；真实燃烧不会这样倒放','化学反应在现实中都能直接倒放'],correct:0,hint:'撤回只是学习模型中的时间轴，不代表真实可逆反应。'}]},
'ce02':{title:'为什么化学方程式必须配平',intro:'只改化学式前的系数，让反应前后每种原子数量相同。',stages:[{title:'左右原子数相等吗？',instruction:'点 H₂、O₂、H₂O 下方的＋或－，配平 H₂ + O₂ → H₂O。',type:'balance',actions:[],need:['balanced'],question:'为什么不能把 H₂O 改写成 H₂O₂？',options:['下标决定物质组成；配平只能改变前面的系数','下标和系数可以随意互换'],correct:0,hint:'比较 H 与 O 两行原子总数；试试 2H₂ + O₂ → 2H₂O。'}, {title:'检查最简整数比',instruction:'点“放大系数”观察仍守恒，再点“化为最简”。',type:'simplify',actions:[['double','放大系数'],['simple','化为最简']],need:['double','simple'],question:'为什么最终通常写 2:1:2？',options:['它是这组化学式的最简整数系数比','4:2:4 表示原子不守恒'],correct:0,hint:'4:2:4 也守恒，但可同时除以 2。'}]}
};
const id=document.body.dataset.id,l=lessons[id];if(!l)return;const $=s=>document.querySelector(s);let stage=0,state={},selected=-1,passed=false,mistakes=0;const s=()=>l.stages[stage];function reset(){state={h:0,o:0,water:0,coeff:[1,1,1]};selected=-1;passed=false;mistakes=0;render()};const has=x=>!!state[x];const chip=(label,n,klass='')=>`<span class="particle ${klass}">${label}${n?` × ${n}`:''}</span>`;
function scene(){let t=s().type;
if(t==='soap')return `<div class="cups"><div class="cup"><b>硬水</b><div class="ions">Ca²⁺　Mg²⁺</div><div class="foam">${has('hard')?'▁ ▂':'—'}</div></div><div class="cup"><b>软水</b><div class="ions">钙镁离子较少</div><div class="foam">${has('soft')?'▂ ▆ █':'—'}</div></div></div><p>肥皂等量；泡沫高低为示意，不是定量实验。</p>`;
if(t==='boil')return `<div class="cup center"><b>硬水 → ${has('boil')?'部分暂时硬度降低':'待处理'}</b><div class="ions">${has('boil')?'部分钙镁成分形成沉积；仍可能有溶解物':'Ca²⁺　Mg²⁺'}</div></div><p>不同硬度来源处理效果不同；不能凭此认定可直接饮用。</p>`;
if(t==='rise')return `<div class="rise-box"><span class="air">空气</span><span class="balloon ${has('rise')?'up':''}">H₂</span></div><p>${has('rise')?'模型中的 H₂ 向上移动；燃烧风险仍须注意。':'点按钮观察 H₂ 的运动趋势。'}</p>`;
if(['burn','atoms','reverse'].includes(t)){let reaction=has('react')||has('again');if(t==='reverse'){state.h=2;state.o=1}return `<div class="molecules"><div><b>反应前</b><div>${chip('H₂',state.h,'hydrogen')}${chip('O₂',state.o,'oxygen')}</div><small>H ${state.h*2} · O ${state.o*2}</small></div><strong>→</strong><div><b>反应后</b><div>${reaction?chip('H₂O',2,'water'):chip('待重组')}</div><small>${reaction?'H 4 · O 2':'等待'}</small></div></div><p>H₂ 是氢气，O₂ 是氧气，H₂O 是水；圆片表示粒子组，不是实际大小。</p>`}
if(t==='filter')return `<div class="flow">${chip('盐水')}<span>→ 普通滤纸 →</span>${chip(has('filter')?'滤液：水＋溶解盐':'待观察')}</div><p>${has('filter')?'滤纸上未留下已溶解的盐。':'先观察盐的去向。'}</p>`;
if(t==='evaporate')return `<div class="cups"><div class="cup"><b>水</b><div class="level" style="height:${Math.max(15,80-(state.evaporate||0)*32)}%"></div></div><div class="cup"><b>盐晶体</b><div class="crystals">${'◆ '.repeat(state.evaporate||0)||'—'}</div></div></div><p>蒸发 ${state.evaporate||0}/2；水变成蒸气离开，盐逐渐析出。</p>`;
if(t==='balance'){let [a,b,c]=state.coeff,Hl=2*a,Ol=2*b,Hr=2*c,Or=c;return `<div class="equation">${['H₂','O₂','H₂O'].map((f,i)=>`<div class="formula"><button data-coeff="${i}" data-delta="-1" aria-label="减少${f}系数">−</button><b>${state.coeff[i]} ${f}</b><button data-coeff="${i}" data-delta="1" aria-label="增加${f}系数">＋</button></div>${i===0?'<strong>＋</strong>':i===1?'<strong>→</strong>':''}`).join('')}</div><div class="atom-count"><span>H：左 ${Hl} ｜右 ${Hr} ${Hl===Hr?'✓':'≠'}</span><span>O：左 ${Ol} ｜右 ${Or} ${Ol===Or?'✓':'≠'}</span></div><p>系数放在化学式前；下标 ₂ 属于物质本身。</p>`}
if(t==='simplify')return `<div class="equation big">${has('double')&&!has('simple')?'4H₂ + 2O₂ → 4H₂O':'2H₂ + O₂ → 2H₂O'}</div><p>${has('double')&&!has('simple')?'H8 O4 = H8 O4，但系数可约分。':'H4 O2 = H4 O2，最简整数比 2:1:2。'}</p>`}
function ready(){let t=s().type;if(t==='burn'||t==='atoms')return state.h===2&&state.o===1&&has('react');if(t==='evaporate')return state.evaporate===2;if(t==='balance')return state.coeff.join(',')==='2,1,2';return s().need.every(has)}
function render(){let done=stage>=l.stages.length;$('#progress').textContent=done?'完成':`第 ${stage+1}/${l.stages.length} 关`;$('#stage').innerHTML=done?`<h2>完成：${l.title}</h2><p>你亲手改变模型、观察结果并解释了现象。</p><a class="button" href="../index.html">返回知识地图 →</a>`:`<h2>${s().title}</h2><p class="instruction">${s().instruction}</p><div class="workbench"><section><h3>观察画面</h3><div class="scene">${scene()}</div></section><section><h3>动手改变</h3><div class="actions">${s().actions.map(([a,label])=>`<button data-act="${a}" ${a==='react'&&!(state.h===2&&state.o===1)||a==='again'&&!has('undo')||a==='simple'&&!has('double')?'disabled':''}>${label}</button>`).join('')}</div><h3>看过再判断</h3><p>${s().question}</p><div class="choices">${s().options.map((v,i)=>`<button data-choice="${i}" aria-pressed="${selected===i}">${v}</button>`).join('')}</div></section></div>`;$('#back').disabled=stage===0;$('#check').hidden=done;$('#next').hidden=done||!passed;$('#message').textContent=done?'':$('#message').textContent;$('#message').className=passed?'good':''}
$('#stage').addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.choice!==undefined){selected=Number(b.dataset.choice);render();return}if(b.dataset.coeff!==undefined){let i=+b.dataset.coeff;state.coeff[i]=Math.max(1,Math.min(4,state.coeff[i]+Number(b.dataset.delta)));passed=false;render();return}let a=b.dataset.act;if(!a)return;if(a==='h'||a==='o')state[a]=Math.min(a==='h'?2:1,state[a]+1);else if(a==='evaporate')state[a]=Math.min(2,(state[a]||0)+1);else if(a==='undo'){state.undo=true;state.react=false;state.again=false}else if(a==='again'){state.again=true;state.react=true}else state[a]=true;passed=false;$('#message').textContent='';render()});
$('#check').onclick=()=>{if(!ready()){$('#message').textContent='先完成画面中的操作。提示：'+s().hint;return}if(selected!==s().correct){mistakes++;$('#message').textContent='再观察一次：'+s().hint;return}passed=true;$('#message').textContent='判断正确。'+(stage===l.stages.length-1?'本课完成。':'进入下一关。');render()};$('#next').onclick=()=>{if(!passed)return;stage++;reset();$('#message').textContent=''};$('#back').onclick=()=>{if(stage){stage--;reset();$('#message').textContent=''}};$('#restart').onclick=()=>{stage=0;reset();$('#message').textContent=''};reset();
})();
