(()=>{'use strict';const $=s=>document.querySelector(s),id=document.body.dataset.id;
const labs={
'cp01-04':{title:'实验室制取、收集与检验氧气',stages:[
{kind:'prep',heading:'制得氧气的概念模型',task:'点“加入催化剂”观察过氧化氢分解的气泡。',choices:[['O₂','气泡代表生成氧气 O₂'],['H₂','气泡是氢气 H₂'],['MnO₂','二氧化锰变成氧气']],correct:'O₂',tip:'过氧化氢在二氧化锰催化下分解为水和氧气；二氧化锰不是氧气的来源。'},
{kind:'collect',heading:'收集与检验气体',task:'点“开始收集”两次装满示意集气瓶，再点“带火星木条检验”。',choices:[['复燃','木条复燃，支持氧气判断'],['熄灭','木条熄灭，说明必是氧气'],['颜色','只看颜色即可确认氧气']],correct:'复燃',tip:'氧气可用排水法收集，带火星木条复燃是常用检验现象；真实实验由教师实施。'}]},
'cp01-05':{title:'催化剂与催化作用',stages:[
{kind:'rate',heading:'比较相同起点的快慢',task:'选择“未加催化剂”和“有 MnO₂”，点推进两次比较反应进度。',choices:[['快','有 MnO₂ 的模型反应较快'],['多','有 MnO₂ 必然产生更多最终氧气'],['消耗','MnO₂ 变成氧气被消耗']],correct:'快',tip:'催化剂改变反应速率；在相同量过氧化氢充分反应时，不凭催化剂增加理论氧气总量。'},
{kind:'reuse',heading:'终点时催化剂如何？',task:'点“推进到终点”，比较两条进度条和 MnO₂ 标记。',choices:[['不变','终点产气总量相同，MnO₂ 化学性质和质量不变'],['更多','有催化剂的终点产气总量更多'],['用尽','催化剂被反应完全用尽']],correct:'不变',tip:'催化剂在反应前后质量和化学性质不变；它改变速率，不改变该反应的产物种类和理论产量。'}]},
'cp01-06':{title:'化合、分解与氧化反应',stages:[
{kind:'combine',heading:'碳与氧气生成二氧化碳',task:'点“形成 CO₂”观察反应前后 C 与 O 原子数量。',choices:[['双重','既是化合反应，也是氧化反应'],['分解','这是分解反应'],['消失','氧原子在反应中消失']],correct:'双重',tip:'C+O₂→CO₂ 是多种反应物生成一种产物的化合反应，也是碳与氧气发生的氧化反应。'},
{kind:'decompose',heading:'过氧化氢分解',task:'逐次加入两个 H₂O 和一个 O₂，对照 2H₂O₂ 的原子总数。',choices:[['分解','一种反应物生成两种产物，是分解反应'],['化合','这是化合反应'],['丢失','产物比反应物少了氧原子']],correct:'分解',tip:'2H₂O₂→2H₂O+O₂；左、右都是 4 个 H 和 4 个 O 原子。反应类型与是否需要催化剂是不同问题。'}]},
'cp02-01':{title:'水的组成与电解水',stages:[
{kind:'split',heading:'两份水怎样变成两种气体？',task:'点“加入水分子”两次，再点“演示电解”观察 2H₂ 与 O₂。',choices:[['守恒','2H₂O → 2H₂ + O₂，H 和 O 原子守恒'],['消失','氧原子消失'],['相等','氢气与氧气体积总是 1:1']],correct:'守恒',tip:'两个水分子共 4H、2O；模型重组为两个 H₂ 与一个 O₂。相同条件下气体体积约 2:1。'},
{kind:'electrode',heading:'两个电极各收集什么？',task:'点“观察阴极”与“观察阳极”，比较两管气体体积。',choices:[['阴极','阴极收集氢气，阳极收集氧气'],['阳极','阳极收集氢气，阴极收集氧气'],['同种','两极是同一种气体']],correct:'阴极',tip:'阴极氢气、阳极氧气；在相同条件下体积约 2:1。实际装置常用适当电解质改善导电，图未表示。'}]},
'cp02-02':{title:'水的净化：沉降、过滤、吸附',stages:[
{kind:'settle',heading:'先让大颗粒沉降',task:'点“等待沉降”，观察泥沙下移，溶解盐仍在水中。',choices:[['泥沙','较大不溶颗粒可沉降'],['盐','溶解盐全部沉底'],['饮用','沉降后即可直接饮用']],correct:'泥沙',tip:'沉降使部分悬浮颗粒落到底部；不能据此断定已除去溶解物或微生物。'},
{kind:'filter',heading:'过滤能拦住什么？',task:'点“经过滤纸”，观察不溶性颗粒留在滤纸上。',choices:[['颗粒','过滤可截留不溶性固体颗粒'],['盐','普通滤纸可完全去除溶解盐'],['安全','滤液必定可直接饮用']],correct:'颗粒',tip:'普通滤纸主要分离不溶性固体；溶解盐通常仍在水中，澄清不等于安全饮用。'},
{kind:'adsorb',heading:'吸附能改变哪些现象？',task:'点“加入活性炭示意”，观察颜色标记减弱，盐仍在。',choices:[['部分','可吸附部分色味物质，效果依材料和条件而变'],['全部','能保证除去所有溶解盐与病原体'],['纯水','立即得到纯水']],correct:'部分',tip:'活性炭可吸附某些色味和有机物，不保证去除所有溶解物或微生物；饮用水还须按适用规范处理。'}]}
};
const lab=labs[id];let learner=localStorage.getItem('learning-lab:learner')||'学习者一';const key=()=>`learning-lab:v1:${learner}:${id}`,read=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}};let saved=read(),stage=Math.max(0,Math.min(lab.stages.length,Number(saved.stage)||0)),step=0,choice='',flags={},answer='',tone='',message='',errors=saved.errors||0,hints=saved.hints||0;const spec=()=>lab.stages[Math.min(stage,lab.stages.length-1)],done=()=>stage===lab.stages.length,save=()=>localStorage.setItem(key(),JSON.stringify({stage,errors,hints,updated:new Date().toISOString()}));
function board(){let s=spec(),k=s.kind;if(k==='prep'||k==='collect')return `<div class="vessel">${k==='prep'?'<span class="solid">H₂O₂　'+(step?'MnO₂':'')+'</span>':`<span class="solid">集气瓶</span>`}${Array.from({length:k==='prep'&&step?6:k==='collect'?step*3:0},()=>'<span class="bubble">O₂</span>').join('')}</div><div class="process-status">${k==='prep'?(step?'产生 O₂ 气泡 · MnO₂ 催化':'过氧化氢 H₂O₂ · 等待操作'):`收集 ${step}/2 份 · ${flags.test?'带火星木条复燃示意':'尚未检验'}`}</div><p class="mini-caption">仅表示物质变化与操作次序，不表示真实装置、剂量或实验操作。</p>`;
if(k==='rate'||k==='reuse'){let a=k==='rate'?Math.min(6,step*1):6,b=k==='rate'?Math.min(6,step*3):6;return `<div class="mass-chart"><div class="mass-row ${flags.plain?'focus':''}"><span>无催化剂</span><span class="mass-track"><span class="mass-fill" style="display:block;width:${a/6*100}%"></span></span><b>${a}/6</b></div><div class="mass-row ${flags.cat?'focus':''}"><span>有 MnO₂</span><span class="mass-track"><span class="mass-fill" style="display:block;width:${b/6*100}%"></span></span><b>${b}/6</b></div></div><div class="process-status">${k==='reuse'&&step?'都到终点 · MnO₂ 标记仍在':'同量 H₂O₂ 的反应进度示意'}</div><p class="mini-caption">进度数字是教学模型，不是实测速率；两组充分反应的终点总量相同。</p>`}
if(k==='combine'||k==='decompose')return `<div class="diagram"><span class="block">${k==='combine'?'C + O₂':'2H₂O₂'}<small> · ${k==='combine'?'C1 O2':'H4 O4'}</small></span><span>→</span><span class="block ${step?'done':''}">${k==='combine'?(step?'CO₂ · C1 O2':'待生成'):step?`${Math.min(step,2)}H₂O${step>=3?' + O₂':''}`:'待组合'}</span></div><div class="process-status">${k==='decompose'?`产物模型：H₂O ${Math.min(step,2)} / 2，O₂ ${step>=3?1:0} / 1`:(step?'原子数相同，排列改变':'点击生成，观察原子数')}</div><p class="mini-caption">反应图仅表示守恒及反应类型，不表示反应机理、具体条件或可自行操作。</p>`;
if(k==='split'&&step<3)return `<div class="diagram">${Array.from({length:step},()=>'<span class="water-unit" aria-label="一个水分子，两个氢原子和一个氧原子"><span>H</span><span>O</span><span>H</span></span>').join('')||'<span class="block">待加入水分子</span>'}</div><div class="process-status">已加入 ${step} / 2 个 H₂O 分子 ${step===2?'· 可观察电解后原子重组':''}</div><p class="mini-caption">每个 H₂O 含两个 H 和一个 O；演示电解后会重新组合，不会消失。</p>`;
if(k==='split'||k==='electrode')return `<div class="gas-tubes"><div class="gas-col ${flags.cathode?'focus':''}"><span class="gas-fill" style="height:${k==='split'&&step<3?38:120}px">${k==='electrode'?'阴极':'H₂'} · ${k==='split'&&step<3?'?':'2 份'}</span></div><div class="gas-col o ${flags.anode?'focus':''}"><span class="gas-fill" style="height:${k==='split'&&step<3?38:72}px">${k==='electrode'?'阳极':'O₂'} · ${k==='split'&&step<3?'?':'1 份'}</span></div></div><div class="process-status">${k==='split'?step<2?`已加入 ${step} / 2 个 H₂O 分子`:step===2?'2H₂O · 等待电解示意':'2H₂O → 2H₂ + O₂ · H4 O2 均守恒':`阴极${flags.cathode?'已观察':'未观察'} · 阳极${flags.anode?'已观察':'未观察'}`}</div><p class="mini-caption">气体体积比是相同条件下的约值；并非直接按水分子个数测量或鼓励自行通电实验。</p>`;
return `<div class="water-tank">${k==='adsorb'?'':Array.from({length:5},(_,i)=>`<span class="grain" style="left:${18+i*16}%;top:${step?(k==='settle'?83:48):15+i*12}%"></span>`).join('')}${k==='filter'&&step?'<span class="filter-shape"></span>':''}${k==='adsorb'&&!step?'<span class="dye"></span>':''}<span class="salt">溶解盐仍在</span></div><div class="process-status">${k==='settle'?step?'泥沙下沉；水中仍可能有其他杂质':'浑浊水中有悬浮泥沙':k==='filter'?step?'滤纸截留不溶颗粒；盐仍溶于水':'待过滤的浑浊水':step?'部分色味标记减弱；盐仍在':'颜色/气味标记示意'}</div><p class="mini-caption">流程是概念模型，澄清水并不等于安全饮用水。</p>`}
function controls(){let k=spec().kind;if(k==='prep')return `<button data-act="catalyst" ${step?'disabled':''}>加入催化剂 MnO₂</button>`;if(k==='collect')return `<button data-act="collect" ${step>=2?'disabled':''}>开始收集 O₂</button><button data-act="test" ${step<2||flags.test?'disabled':''}>带火星木条检验</button><button data-act="undo" ${!step?'disabled':''}>↶ 撤回收集</button>`;if(k==='rate')return `<button data-act="observe" data-val="plain">观察无催化剂</button><button data-act="observe" data-val="cat">观察有 MnO₂</button><button data-act="advance" ${step>=2?'disabled':''}>推进同一时间步</button><button data-act="undo" ${!step?'disabled':''}>↶ 撤回一步</button>`;if(k==='reuse')return `<button data-act="finish" ${step?'disabled':''}>推进到终点</button>`;if(k==='combine')return `<button data-act="form" ${step?'disabled':''}>形成 CO₂</button><button data-act="undo" ${!step?'disabled':''}>↶ 撤回</button>`;if(k==='decompose')return `<button data-act="addwater" ${step>=2?'disabled':''}>＋ H₂O</button><button data-act="addoxygen" ${step!==2?'disabled':''}>＋ O₂</button><button data-act="undo" ${!step?'disabled':''}>↶ 撤回一步</button>`;if(k==='split')return `<button data-act="water" ${step>=2?'disabled':''}>＋ 加入水分子</button><button data-act="electrolyse" ${step!==2?'disabled':''}>演示电解</button><button data-act="undo" ${!step?'disabled':''}>↶ 撤回</button>`;if(k==='electrode')return `<button data-act="cathode">观察阴极</button><button data-act="anode">观察阳极</button>`;return `<button data-act="process" ${step?'disabled':''}>${k==='settle'?'等待沉降':k==='filter'?'经过滤纸':'加入活性炭示意'}</button><button data-act="undo" ${!step?'disabled':''}>↶ 返回处理前</button>`}
function ready(){let k=spec().kind;if(k==='prep')return step===1;if(k==='collect')return step===2&&flags.test;if(k==='rate')return step===2&&flags.plain&&flags.cat;if(k==='reuse'||k==='combine'||['settle','filter','adsorb'].includes(k))return step===1;if(k==='decompose'||k==='split')return step===3;return flags.cathode&&flags.anode}
function render(){let s=spec();$('#learner').value=learner;$('#steps').innerHTML=lab.stages.map((_,i)=>`<span class="${i<stage?'done':''}"></span>`).join('');$('#lab').classList.toggle('completed',done());$('#lab').innerHTML=done()?`<div class="stage-head"><h2>完成：${lab.title}</h2></div><p class="task">你已经操作模型并判断了结果。可以返回知识地图继续学习。</p>`:`<div class="stage-head"><div><span class="badge">第 ${stage+1} / ${lab.stages.length} 关</span><h2>${s.heading}</h2></div></div><p class="task">${s.task}</p><div class="workbench"><div class="display"><h3>观察模型</h3><div class="process-scene">${board()}</div></div><div class="tools"><h3>动手改变画面</h3><div class="select-controls">${controls()}</div><h3>观察后判断</h3><div class="tiles">${s.choices.map(([v,label])=>`<button data-act="choose" data-val="${v}" aria-pressed="${answer===v}">${label}</button>`).join('')}</div><p class="explain">先操作模型，再选择并检查。</p></div></div>`;$('#feedback').textContent=message;$('#feedback').className='feedback '+tone;$('#back').disabled=stage===0;$('#verify').hidden=done();$('#next').hidden=!done()&&tone!=='good';$('#next').textContent=done()?'返回知识地图 →':'下一关 →'}
function resetView(){step=0;choice='';flags={};answer='';tone='';message='';render()}
function fail(text){errors++;message=text+(errors>=2?' 提示：'+spec().tip:'');if(errors>=2)hints++;tone='bad';save();render()}
$('#lab').addEventListener('click',e=>{let b=e.target.closest('button[data-act]');if(!b||b.disabled)return;let a=b.dataset.act,v=b.dataset.val;if(a==='choose')answer=v;else if(a==='observe'){flags[v]=true}else if(a==='catalyst'||a==='finish'||a==='form'||a==='process')step=1;else if(a==='collect'||a==='advance'||a==='addwater'||a==='water')step++;else if(a==='addoxygen'||a==='electrolyse')step=3;else if(a==='test')flags.test=true;else if(a==='cathode'||a==='anode')flags[a]=true;else if(a==='undo'){step=Math.max(0,step-1);flags.test=false}if(tone==='good')tone='';message='';render()});
$('#verify').onclick=()=>{if(!ready())return fail('先完成本关的图形操作，再根据看到的结果判断。');if(answer!==spec().correct)return fail('这个判断与模型不符，请比较粒子、数量或流程状态。');message='正确！'+spec().tip;tone='good';save();render()};$('#next').onclick=()=>{if(done()){location.href='../index.html';return}if(tone!=='good')return;stage++;resetView();save()};$('#back').onclick=()=>{if(stage>0){stage--;resetView();save()}};$('#reset').onclick=()=>{localStorage.removeItem(key());stage=0;errors=0;hints=0;resetView();save()};$('#switch').onclick=()=>{learner=$('#learner').value.trim()||'学习者一';localStorage.setItem('learning-lab:learner',learner);saved=read();stage=Math.max(0,Math.min(lab.stages.length,Number(saved.stage)||0));errors=saved.errors||0;hints=saved.hints||0;resetView()};$('#learner').addEventListener('change',()=>$('#switch').click());resetView();})();
