(()=>{'use strict';const $=s=>document.querySelector(s),id=document.body.dataset.id;
const lessons={
'cb02-04':{title:'地壳、人体和空气中的常见元素',stages:[
{heading:'地壳中哪种元素最多？',task:'点“地壳”，看按质量估计的元素比例。',context:'地壳',bars:[['氧 O',46.6],['硅 Si',27.7],['其他',25.7]],choices:[['O','氧 O'],['Si','硅 Si'],['Fe','铁 Fe']],correct:'O',tip:'地壳元素按质量估计，氧约 46.6%，硅约 27.7%；元素不是氧气或单质硅。'},
{heading:'人体质量主要来自哪些元素？',task:'点“人体”，看质量构成，再选占比最多的元素。',context:'人体',bars:[['氧 O',65],['碳 C',18.5],['氢 H',9.5],['其他',7]],choices:[['O','氧 O'],['H','氢 H'],['N','氮 N']],correct:'O',tip:'人体按质量估计氧最多，约 65%；含氧不表示人体里都是氧气。'},
{heading:'干燥空气主要是哪种气体？',task:'点“干燥空气”，观察气体体积分数；留意这里统计的是气体。',context:'干燥空气',bars:[['氮气 N₂',78.09],['氧气 O₂',20.95],['其他气体',0.96]],choices:[['N₂','氮气 N₂'],['O₂','氧气 O₂'],['N','氮元素 N']],correct:'N₂',tip:'干燥空气按体积主要是氮气 N₂，约 78%；前两关比较元素质量，这一关比较气体体积。'}]},
'cb03-01':{title:'化学式的意义与读法',stages:[
{heading:'拼出一个水分子',task:'点 H 两次、O 一次，让图中出现 2 个 H 与 1 个 O。',units:['H','O'],target:{H:2,O:1},formula:'H₂O',choices:[['水','H₂O 读“水”'],['氢气','H₂O 读“氢气”'],['氧气','H₂O 读“氧气”']],correct:'水',tip:'H₂O 是水的化学式；一个水分子含 2 个氢原子和 1 个氧原子。'},
{heading:'拼出一个二氧化碳分子',task:'点 C 一次、O 两次，观察分子内的原子个数。',units:['C','O'],target:{C:1,O:2},formula:'CO₂',choices:[['二氧化碳','CO₂ 读“二氧化碳”'],['一氧化碳','CO₂ 读“一氧化碳”'],['碳酸','CO₂ 读“碳酸”']],correct:'二氧化碳',tip:'CO₂ 是二氧化碳的化学式；右下角 2 表示一个分子中有两个氧原子。'}]},
'cb03-02':{title:'化学式中数字的位置和意义',stages:[
{heading:'从 H 调出 2H₂',task:'从 H 开始，调节前面的系数到 2、右下角下标到 2，观察分子数和总原子数。',numeral:true,target:{coef:2,sub:2},choices:[['4','一共有 4 个氢原子'],['2','一共有 2 个氢原子'],['1','只有 1 个分子']],correct:'4',tip:'2H₂ 表示 2 个氢分子，每个分子含 2 个氢原子，共 4 个氢原子。'},
{heading:'从 H 调出 2H',task:'调节系数到 2、下标到 1，观察两个独立原子。',numeral:true,target:{coef:2,sub:1},choices:[['原子','2H 表示 2 个氢原子'],['分子','2H 表示 2 个氢分子'],['元素','2H 表示 2 种氢元素']],correct:'原子',tip:'2H 表示 2 个氢原子；系数数的是整个符号表示的微粒，下标数的是一个微粒内的原子。'}]},
'cb03-03':{title:'化合价与常见原子团',stages:[
{heading:'让镁与氧电荷抵消',task:'分别加入 Mg²⁺ 与 O²⁻，让总电荷归零。',ions:[['Mg²⁺',2],['O²⁻',-2]],target:[1,1],choices:[['中性','+2 与 −2 相抵，整体不带电'],['正','整体带 +2 电'],['负','整体带 −2 电']],correct:'中性',tip:'在这些化合物中镁常显 +2、氧常显 −2；一个 Mg²⁺ 与一个 O²⁻ 的电荷相抵。'},
{heading:'把 OH⁻ 当成一个原子团',task:'加入一个 Ca²⁺ 和两个 OH⁻，看整体电荷。',ions:[['Ca²⁺',2],['OH⁻',-1]],target:[1,2],choices:[['原子团','OH⁻ 是氢氧根原子团'],['元素','OH⁻ 是一种元素'],['原子','OH⁻ 是一个原子']],correct:'原子团',tip:'氢氧根 OH⁻ 是带 −1 电荷的原子团；两个 OH⁻ 与一个 Ca²⁺ 的电荷相抵。'}]},
'cb03-04':{title:'由化合价书写化学式',stages:[
{heading:'组合镁与氯',task:'加入一个 Mg²⁺ 和两个 Cl⁻，选出电中性的化学式。',ions:[['Mg²⁺',2],['Cl⁻',-1]],target:[1,2],formula:'MgCl₂',choices:[['MgCl₂','MgCl₂'],['MgCl','MgCl'],['Mg₂Cl','Mg₂Cl']],correct:'MgCl₂',tip:'Mg 显 +2，Cl 常显 −1；两个 Cl 与一个 Mg 相配，写 MgCl₂。'},
{heading:'组合钙与氢氧根',task:'加入一个 Ca²⁺ 和两个 OH⁻，观察原子团的整体数量。',ions:[['Ca²⁺',2],['OH⁻',-1]],target:[1,2],formula:'Ca(OH)₂',choices:[['Ca(OH)₂','Ca(OH)₂'],['CaOH₂','CaOH₂'],['Ca₂OH','Ca₂OH']],correct:'Ca(OH)₂',tip:'两个氢氧根作为两个完整原子团，写 Ca(OH)₂；括号外的 2 作用于整个 OH。'}]}
};
const course=lessons[id];let learner=localStorage.getItem('learning-lab:learner')||'学习者一';const key=()=>`learning-lab:v1:${learner}:${id}`;const read=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}};let saved=read(),stage=Math.min(course.stages.length,Math.max(0,Number(saved.stage)||0)),counts={},coef=1,sub=1,context='',answer='',operated=false,feedback='',tone='',mistakes=saved.mistakes||0,hints=saved.hints||0;const spec=()=>course.stages[Math.min(stage,course.stages.length-1)],done=()=>stage===course.stages.length,persist=()=>localStorage.setItem(key(),JSON.stringify({stage,mistakes,hints,updated:new Date().toISOString()}));
function tokens(s){return s==='OH⁻'?'<span class="unit-group"><span class="unit o">O</span><span class="unit h">H</span></span>':`<span class="unit ${s.toLowerCase().startsWith('h')?'h':s.toLowerCase().startsWith('o')?'o':'ion'}">${s}</span>`}
function board(){const s=spec();if(s.context)return `<div class="formula">${context||'请选择观察场景'}</div>${context===s.context?s.bars.map(([name,pct])=>`<div class="bar-row"><span>${name}</span><span class="bar-track"><span class="bar-fill" style="display:block;width:${pct}%"></span></span><b>${pct}%</b></div>`).join(''):'<p>点击右侧场景按钮，显示组成比例。</p>'}<span class="smallnote">${s.context==='干燥空气'?'气体体积分数':'元素质量分数'}；约值</span>`;
if(s.numeral)return `<div class="formula">${coef>1?coef:''}H${sub>1?`<sub>${sub}</sub>`:''}</div><div class="unit-row">${Array.from({length:coef},()=>`<span class="unit-group">${Array.from({length:sub},()=>tokens('H')).join('')}</span>`).join('')}</div><div class="count">${coef} ${sub>1?'个分子':'个原子'} · 合计 ${coef*sub} 个氢原子</div>`;
if(s.ions){let charge=s.ions.reduce((n,[,c],i)=>n+c*(counts[i]||0),0);return `<div class="unit-row">${s.ions.map(([sym],i)=>Array.from({length:counts[i]||0},()=>tokens(sym)).join('')).join('')||'<span>从右侧加入粒子</span>'}</div><div class="count">总电荷：${charge>0?'+'+charge:charge}</div>${s.formula&&s.target.every((n,i)=>(counts[i]||0)===n)?`<div class="formula">${s.formula}</div>`:''}<div class="smallnote">此图借离子电荷理解常见化合价的配比。化合价描述元素在化合物中的结合关系，离子电荷是粒子实际所带的电荷；图形不表示混合游离离子就发生反应。</div>`}
return `<div class="unit-row">${s.units.map(sym=>Array.from({length:counts[sym]||0},()=>tokens(sym)).join('')).join('')||'<span>从右侧加入原子</span>'}</div><div class="count">${s.units.map(sym=>`${sym}：${counts[sym]||0}`).join('　')}</div>${Object.entries(s.target).every(([k,n])=>(counts[k]||0)===n)?`<div class="formula">${s.formula}</div>`:''}<div class="smallnote">球形只是计数模型，不表示真实大小、键角或制备过程。</div>`}
function controls(){const s=spec();if(s.context)return `<button data-act="context" data-val="${s.context}">查看${s.context}组成</button>`;if(s.numeral)return `<span>前面的系数</span><button data-act="coef" data-val="-1" ${coef<=1?'disabled':''}>−</button><b>${coef}</b><button data-act="coef" data-val="1" ${coef>=3?'disabled':''}>＋</button><span>右下角下标</span><button data-act="sub" data-val="-1" ${sub<=1?'disabled':''}>−</button><b>${sub}</b><button data-act="sub" data-val="1" ${sub>=3?'disabled':''}>＋</button>`;
if(s.ions)return s.ions.map(([sym],i)=>`<button data-act="add" data-val="${i}">＋ ${sym}</button><button data-act="remove" data-val="${i}" ${!counts[i]?'disabled':''}>− ${sym}</button>`).join('');return s.units.map(sym=>`<button data-act="add" data-val="${sym}">＋ ${sym}</button><button data-act="remove" data-val="${sym}" ${!counts[sym]?'disabled':''}>− ${sym}</button>`).join('')}
function ready(){const s=spec();if(s.context)return context===s.context;if(s.numeral)return operated&&coef===s.target.coef&&sub===s.target.sub;if(s.ions)return operated&&s.target.every((n,i)=>(counts[i]||0)===n);return operated&&Object.entries(s.target).every(([k,n])=>(counts[k]||0)===n)}
function render(){const s=spec();$('#learner').value=learner;$('#steps').innerHTML=course.stages.map((_,i)=>`<span class="${i<stage?'done':''}"></span>`).join('');$('#lab').classList.toggle('completed',done());$('#lab').innerHTML=done()?`<div class="stage-head"><h2>完成：${course.title}</h2></div><p class="task">你已改变模型并解释了结果。可以返回知识地图或重新开始。</p>`:`<div class="stage-head"><div><span class="badge">第 ${stage+1} / ${course.stages.length} 关</span><h2>${s.heading}</h2></div></div><p class="task">${s.task}</p><div class="workbench"><div class="display"><h3>动手观察</h3><div class="symbol-scene">${board()}</div></div><div class="tools"><h3>改变模型</h3><div class="control-group">${controls()}</div><h3>观察后判断</h3><div class="tiles">${s.choices.map(([val,label])=>`<button class="formula-choice" data-act="choose" data-val="${val}" aria-pressed="${answer===val}">${label}</button>`).join('')}</div><p class="explain">先操作左侧模型，再选择并检查。</p></div></div>`;$('#feedback').textContent=feedback;$('#feedback').className='feedback '+tone;$('#back').disabled=stage===0;$('#verify').hidden=done();$('#next').hidden=!done()&&tone!=='good';$('#next').textContent=done()?'返回知识地图 →':'下一关 →'}
function resetView(){counts={};coef=1;sub=1;context='';answer='';operated=false;feedback='';tone='';render()}
function fail(t){mistakes++;feedback=t+(mistakes>=2?' 提示：'+spec().tip:'');if(mistakes>=2)hints++;tone='bad';persist();render()}
$('#lab').addEventListener('click',e=>{const b=e.target.closest('button[data-act]');if(!b||b.disabled)return;const act=b.dataset.act,val=b.dataset.val;if(act==='choose')answer=val;else if(act==='context'){context=val;operated=true}else if(act==='add'){counts[val]=(counts[val]||0)+1;operated=true}else if(act==='remove'){counts[val]=Math.max(0,(counts[val]||0)-1);operated=true}else if(act==='coef'){coef+=Number(val);operated=true}else if(act==='sub'){sub+=Number(val);operated=true}if(tone==='good')tone='';feedback='';render()});
$('#verify').onclick=()=>{if(!ready())return fail('先把模型调成题目要求的数量或场景，观察画面再判断。');if(answer!==spec().correct)return fail('判断还不准确。请比较图中的粒子数量、位置和说明。');feedback='正确！'+spec().tip;tone='good';persist();render()};$('#next').onclick=()=>{if(done()){location.href='../index.html';return}if(tone!=='good')return;stage++;resetView();persist()};$('#back').onclick=()=>{if(stage>0){stage--;resetView();persist()}};$('#reset').onclick=()=>{localStorage.removeItem(key());stage=0;mistakes=0;hints=0;resetView();persist()};$('#switch').onclick=()=>{learner=$('#learner').value.trim()||'学习者一';localStorage.setItem('learning-lab:learner',learner);saved=read();stage=Math.min(course.stages.length,Math.max(0,Number(saved.stage)||0));mistakes=saved.mistakes||0;hints=saved.hints||0;resetView()};$('#learner').addEventListener('change',()=>$('#switch').click());resetView();
})();
