(()=>{'use strict';const $=s=>document.querySelector(s),id='cb01-04';let learner=localStorage.getItem('learning-lab:learner')||'学习者一';const key=()=>`learning-lab:v1:${learner}:${id}`,read=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}};let saved=read(),stage=Math.max(0,Math.min(3,Number(saved.stage)||0)),evidence=saved.evidence||{mistakes:{},hints:0},state={},passed=false,errors=0,message='',tone='',timer=null;const persist=()=>localStorage.setItem(key(),JSON.stringify({stage,evidence,updated:new Date().toISOString()}));
function stop(){if(timer){clearInterval(timer);timer=null}}
function init(){stop();state=stage===0?{added:false,tick:0,answer:null}:stage===1?{added:false,tick:0,answer:null}:stage===2?{added:false,tick:0,observer:false,answer:null}:{};passed=false;errors=0;message='';tone=''}
const rnd=(n,k)=>{const x=Math.sin(n*127.1+k*311.7)*43758.5453;return x-Math.floor(x)};
const clamp=x=>Math.max(5,Math.min(94,x));
function dots(kind,p){if(!state.added)return '';return Array.from({length:48},(_,i)=>{const x=kind==='room'?clamp(10+(rnd(i,3)*81)*p):clamp(50+(rnd(i,3)-.5)*(5+83*p));const y=kind==='room'?clamp(18+rnd(i,4)*66):clamp(61+(rnd(i,4)-.5)*(5+61*p));return `<i class="dot" style="left:${x.toFixed(1)}%;top:${y.toFixed(1)}%;opacity:${kind==='room'&&state.tick===0?.7:.9}" aria-hidden="true"></i>`}).join('')}
const track=()=>`<div class="time-track" aria-label="已推进 ${state.tick} / 6 步">${Array.from({length:6},(_,i)=>`<span class="${i<state.tick?'on':''}"></span>`).join('')}</div>`;
const controls=(label)=>`<button type="button" data-action="add" ${state.added?'disabled':''}>${state.added?'✓ 已'+label:'＋ '+label}</button><div class="control-row"><button type="button" data-action="step" ${!state.added||state.tick===6?'disabled':''}>▶ 推进一步</button><button type="button" data-action="play" ${!state.added||state.tick===6||timer?'disabled':''}>⏩ 连续播放</button><button type="button" data-action="pause" ${timer?'':'disabled'}>⏸ 暂停</button></div><button type="button" data-action="rewind" ${state.added?'':'disabled'}>↶ 回到初始状态</button>${track()}<p class="mini">每步是示意时间，不是实测秒数；可以暂停后继续。</p>`;
const choose=(v,label)=>`<button type="button" data-action="choose" data-value="${v}" class="${state.answer===v?'selected':''}" aria-pressed="${state.answer===v}">${label}</button>`;
function first(){return `<div class="stage-head"><div><span class="badge">第 1 关 · 看它散开</span><h2>没有搅拌，色点会怎样？</h2></div></div><p class="task">给静止水的示意模型加一滴色点，推进几步观察分布。</p><div class="workbench"><div class="display"><h3>一杯水 · 剖面示意</h3><div class="scene one"><div class="jar" aria-label="色点扩散模型，当前第 ${state.tick} 步">${dots('water',state.tick/6)}</div></div><div class="readout">${!state.added?'色点尚未加入':state.tick<2?'色点集中在局部':state.tick<4?'更多区域出现色点':'色点分布到杯中更多位置'}</div></div><div class="tools"><h3>实验台</h3>${controls('加入色点')}<h3>这种逐渐散开的现象叫</h3><div class="choice-row">${choose('diffusion','扩散')}${choose('reaction','发生化学反应')}</div></div></div>`}
function second(){const cold=Math.min(1,state.tick/8),warm=Math.min(1,state.tick/4.5);return `<div class="stage-head"><div><span class="badge">第 2 关 · 对照观察</span><h2>只改变温度，谁先散开？</h2></div></div><p class="task">两杯同时放入同量色点，不搅拌。推进相同的时间步数。</p><div class="workbench"><div class="display"><div class="scene"><div><h3>较冷的水</h3><div class="jar cold" aria-label="冷水第 ${state.tick} 步">${dots('water',cold)}</div><p class="caption">${state.tick>=4?'本步仍较集中':'等待同步观察'}</p></div><div><h3>较暖的水</h3><div class="jar warm" aria-label="暖水第 ${state.tick} 步">${dots('water',warm)}</div><p class="caption">${state.tick>=4?'本步已较分散':'等待同步观察'}</p></div></div><div class="readout">${!state.added?'尚未加入色点':state.tick<4?'继续推进，再比较相同时间下的分布范围':`同为第 ${state.tick} 步，暖水中色点分布更广`}</div></div><div class="tools"><h3>同条件对照</h3>${controls('两杯同时加同量色点')}<h3>相同步数下，哪杯更快？</h3><div class="choice-row">${choose('warm','较暖的水')}${choose('cold','较冷的水')}</div><p class="mini">仅温度不同；不模拟对流或实际温度数值。无需自行加热液体。</p></div></div>`}
function third(){return `<div class="stage-head"><div><span class="badge">第 3 关 · 迁移解释</span><h2>房间另一端为何闻到气味？</h2></div></div><p class="task">点击释放气味微粒模型，推进时间，再点远处的观察者。</p><div class="workbench"><div class="display"><h3>房间平面示意</h3><div class="room" aria-label="气味微粒分布，第 ${state.tick} 步"><span class="bottle" aria-hidden="true">🧴</span>${dots('room',Math.min(1,state.tick/5))}<button type="button" class="observer ${state.observer?'selected':''}" data-action="observe">👤 远处观察者</button></div><div class="readout">${!state.added?'还没有释放气味微粒':state.tick<5?'微粒仍在向更大范围分散':state.observer?'远处也能闻到：气味微粒已到达附近':'点远处观察者，查看现象'}</div></div><div class="tools"><h3>观察台</h3>${controls('释放气味微粒')}<h3>主要说明</h3><div class="choice-row">${choose('motion','微粒在不断运动')}${choose('vanish','微粒消失了')}</div><p class="mini">假定房间无明显气流。现实中空气流动也会影响气味传播；此处只看扩散示意。</p></div></div>`}
function summary(){return `<div class="stage-head"><span class="badge">本轮完成</span><h2>看见扩散的线索了！</h2></div><div class="summary"><ol><li>色点从局部散到更大范围，可用微粒不断运动解释。</li><li>本模型中同样的时间，较暖的水中色点散得更快。</li><li>气味能传到远处，气味微粒没有凭空消失。</li></ol><p>${Object.keys(evidence.mistakes).length?'复习建议：回看第 '+Object.keys(evidence.mistakes).join('、')+' 关，再观察并解释。':'试着向家人解释：为什么先在近处闻到气味？'}</p></div><p class="task">学习进度只保存在当前浏览器的学习者档案。</p>`}
function render(){$('#learner').value=learner;$('#steps').innerHTML=[0,1,2].map(i=>`<span class="${i<stage?'done':i===stage?'active':''}"></span>`).join('');$('#lab').innerHTML=[first,second,third,summary][stage]();$('#feedback').textContent=message;$('#feedback').className='feedback '+tone;$('#back').disabled=stage===0;$('#verify').hidden=stage===3;$('#next').hidden=!passed&&stage!==3;$('#next').textContent=stage===3?'返回知识地图 →':'下一关 →'}
function change(){passed=false;message='';tone='';render()}
function fail(reason){errors++;evidence.mistakes[stage+1]=(evidence.mistakes[stage+1]||0)+1;if(errors>=2){evidence.hints++;reason+=' 提示：'+['加入色点后至少推进四步，看它是否逐渐散开。','两杯加入相同的量、同时观察，比较哪杯分布更广。','推进到第五步后点远处观察者；到达说明微粒仍在运动。'][stage]}message=reason;tone='bad';persist();render()}
function verify(){if(stage===0){if(!state.added||state.tick<4)return fail('先加入色点，推进至少四步，观察局部如何变化。');if(state.answer!=='diffusion')return fail('色点散开并不表示产生新物质；选“扩散”。');passed=true;message='对！可用微粒不断运动来解释逐渐散开的现象。';tone='good'}else if(stage===1){if(!state.added||state.tick<4)return fail('先同时放入色点，再推进至少四步，比较同一步数的两杯。');if(state.answer!=='warm')return fail('看同一步数下分布更广的一杯：较暖的水。');passed=true;message='观察到：在这组示意条件下，温度较高时扩散较快。';tone='good'}else if(stage===2){if(!state.added||state.tick<5||!state.observer)return fail('先释放气味微粒，推进到第五步，再点远处观察者。');if(state.answer!=='motion')return fail('闻到气味说明有气味微粒到达了附近，并非它们消失。');passed=true;message='判断正确！不断运动的气味微粒能散到远处。';tone='good'}render()}
function advance(){if(state.tick<6){state.tick++;change()}if(state.tick===6)stop()}
function move(n){stage=n;init();persist();render()}
$('#switch').onclick=()=>{stop();learner=$('#learner').value.trim()||'学习者一';localStorage.setItem('learning-lab:learner',learner);saved=read();stage=Math.max(0,Math.min(3,Number(saved.stage)||0));evidence=saved.evidence||{mistakes:{},hints:0};init();render()};$('#learner').addEventListener('change',()=>$('#switch').click());$('#reset').onclick=()=>{stop();localStorage.removeItem(key());evidence={mistakes:{},hints:0};move(0)};$('#back').onclick=()=>{if(stage>0)move(stage-1)};$('#verify').onclick=verify;$('#next').onclick=()=>{if(stage===3){location.href='../index.html';return}if(passed)move(stage+1)};
$('#lab').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='add'){state.added=true;change()}else if(a==='step'&&state.added){stop();advance()}else if(a==='play'&&state.added&&state.tick<6&&!timer){timer=setInterval(advance,650);render()}else if(a==='pause'){stop();render()}else if(a==='rewind'){stop();state.added=false;state.tick=0;state.observer=false;change()}else if(a==='observe'&&stage===2){if(state.added&&state.tick>=5){state.observer=true;change()}else{message='先释放气味微粒并推进到第五步，再点远处观察者。';tone='bad';render()}}else if(a==='choose'){state.answer=b.dataset.value;change()}});init();render()})();
